// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Settings for creating an AlloyDB cluster.
public struct AlloyDbSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Input only. Initial user to setup during cluster creation.
  /// Required.
  public var initialUser: AlloyDbSettings.UserPassword? = nil

  /// Required. The resource link for the VPC network in which cluster resources
  /// are created and from which they are accessible via Private IP. The network
  /// must belong to the same project as the cluster. It is specified in the
  /// form: "projects/{project_number}/global/networks/{network_id}". This is
  /// required to create a cluster.
  public var vpcNetwork: Swift.String = Swift.String()

  /// Labels for the AlloyDB cluster created by DMS. An object containing a list
  /// of 'key', 'value' pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  public var primaryInstanceSettings: AlloyDbSettings.PrimaryInstanceSettings? = nil

  /// Optional. The encryption config can be specified to encrypt the data disks
  /// and other persistent data resources of a cluster with a
  /// customer-managed encryption key (CMEK). When this field is not
  /// specified, the cluster will then use default encryption scheme to
  /// protect the user data.
  public var encryptionConfig: AlloyDbSettings.EncryptionConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AlloyDbSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AlloyDbSettings().with { $0.initialUser = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let initialUser = CodingKeys(stringValue: "initialUser")
    static let vpcNetwork = CodingKeys(stringValue: "vpcNetwork")
    static let labels = CodingKeys(stringValue: "labels")
    static let primaryInstanceSettings = CodingKeys(stringValue: "primaryInstanceSettings")
    static let encryptionConfig = CodingKeys(stringValue: "encryptionConfig")

    static let _knownKeys: Set<Swift.String> = [
      "initialUser",
      "vpcNetwork",
      "labels",
      "primaryInstanceSettings",
      "encryptionConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.initialUser = try container.decodeIfPresent(
      AlloyDbSettings.UserPassword.self, forKey: .initialUser)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vpcNetwork) {
      self.vpcNetwork = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.primaryInstanceSettings = try container.decodeIfPresent(
      AlloyDbSettings.PrimaryInstanceSettings.self, forKey: .primaryInstanceSettings)
    self.encryptionConfig = try container.decodeIfPresent(
      AlloyDbSettings.EncryptionConfig.self, forKey: .encryptionConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.initialUser, forKey: .initialUser)
    try container.encode(self.vpcNetwork, forKey: .vpcNetwork)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.primaryInstanceSettings, forKey: .primaryInstanceSettings)
    try container.encodeIfPresent(self.encryptionConfig, forKey: .encryptionConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The username/password for a database user. Used for specifying initial
  /// users at cluster creation time.
  public struct UserPassword: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The database username.
    public var user: Swift.String = Swift.String()

    /// The initial password for the user.
    public var password: Swift.String = Swift.String()

    /// Output only. Indicates if the initial_user.password field has been set.
    public var passwordSet: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UserPassword`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserPassword().with { $0.user = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let user = CodingKeys(stringValue: "user")
      static let password = CodingKeys(stringValue: "password")
      static let passwordSet = CodingKeys(stringValue: "passwordSet")

      static let _knownKeys: Set<Swift.String> = [
        "user",
        "password",
        "passwordSet",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .user) {
        self.user = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
        self.password = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .passwordSet) {
        self.passwordSet = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.user, forKey: .user)
      try container.encode(self.password, forKey: .password)
      try container.encode(self.passwordSet, forKey: .passwordSet)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.clouddms.v1.AlloyDbSettings.UserPassword"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Settings for the cluster's primary instance
  public struct PrimaryInstanceSettings: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The ID of the AlloyDB primary instance. The ID must satisfy the
    /// regex expression "[a-z0-9-]+".
    public var id: Swift.String = Swift.String()

    /// Configuration for the machines that host the underlying
    /// database engine.
    public var machineConfig: AlloyDbSettings.PrimaryInstanceSettings.MachineConfig? = nil

    /// Database flags to pass to AlloyDB when DMS is creating the AlloyDB
    /// cluster and instances. See the AlloyDB documentation for how these can be
    /// used.
    public var databaseFlags: [Swift.String: Swift.String] = [:]

    /// Labels for the AlloyDB primary instance created by DMS. An object
    /// containing a list of 'key', 'value' pairs.
    public var labels: [Swift.String: Swift.String] = [:]

    /// Output only. The private IP address for the Instance.
    /// This is the connection endpoint for an end-user application.
    public var privateIp: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PrimaryInstanceSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrimaryInstanceSettings().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")
      static let machineConfig = CodingKeys(stringValue: "machineConfig")
      static let databaseFlags = CodingKeys(stringValue: "databaseFlags")
      static let labels = CodingKeys(stringValue: "labels")
      static let privateIp = CodingKeys(stringValue: "privateIp")

      static let _knownKeys: Set<Swift.String> = [
        "id",
        "machineConfig",
        "databaseFlags",
        "labels",
        "privateIp",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      self.machineConfig = try container.decodeIfPresent(
        AlloyDbSettings.PrimaryInstanceSettings.MachineConfig.self, forKey: .machineConfig)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .databaseFlags)
      {
        self.databaseFlags = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .labels)
      {
        self.labels = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .privateIp) {
        self.privateIp = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encodeIfPresent(self.machineConfig, forKey: .machineConfig)
      try container.encode(self.databaseFlags, forKey: .databaseFlags)
      try container.encode(self.labels, forKey: .labels)
      try container.encode(self.privateIp, forKey: .privateIp)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// MachineConfig describes the configuration of a machine.
    public struct MachineConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The number of CPU's in the VM instance.
      public var cpuCount: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `MachineConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MachineConfig().with { $0.cpuCount = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let cpuCount = CodingKeys(stringValue: "cpuCount")

        static let _knownKeys: Set<Swift.String> = [
          "cpuCount"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .cpuCount) {
          self.cpuCount = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.cpuCount, forKey: .cpuCount)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.clouddms.v1.AlloyDbSettings.PrimaryInstanceSettings.MachineConfig"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.clouddms.v1.AlloyDbSettings.PrimaryInstanceSettings"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// EncryptionConfig describes the encryption config of a cluster that is
  /// encrypted with a CMEK (customer-managed encryption key).
  public struct EncryptionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The fully-qualified resource name of the KMS key.
    /// Each Cloud KMS key is regionalized and has the following format:
    /// projects/[PROJECT]/locations/[REGION]/keyRings/[RING]/cryptoKeys/[KEY_NAME]
    public var kmsKeyName: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EncryptionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EncryptionConfig().with { $0.kmsKeyName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let kmsKeyName = CodingKeys(stringValue: "kmsKeyName")

      static let _knownKeys: Set<Swift.String> = [
        "kmsKeyName"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyName) {
        self.kmsKeyName = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.kmsKeyName, forKey: .kmsKeyName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.clouddms.v1.AlloyDbSettings.EncryptionConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.AlloyDbSettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
