// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for 'ApplyConversionWorkspace' request.
public struct ApplyConversionWorkspaceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the conversion workspace resource for which to apply
  /// the draft tree. Must be in the form of:
  ///  projects/{project}/locations/{location}/conversionWorkspaces/{conversion_workspace}.
  public var name: Swift.String = Swift.String()

  /// Filter which entities to apply. Leaving this field empty will apply all of
  /// the entities. Supports Google AIP 160 based filtering.
  public var filter: Swift.String = Swift.String()

  /// Optional. Only validates the apply process, but doesn't change the
  /// destination database. Only works for PostgreSQL destination connection
  /// profile.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// Optional. Specifies whether the conversion workspace is to be committed
  /// automatically after the apply.
  public var autoCommit: Swift.Bool = Swift.Bool()

  /// Which destination to use when applying the conversion workspace.
  public var destination: OneOf_Destination? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApplyConversionWorkspaceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApplyConversionWorkspaceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let filter = CodingKeys(stringValue: "filter")
    static let dryRun = CodingKeys(stringValue: "dryRun")
    static let autoCommit = CodingKeys(stringValue: "autoCommit")
    static let connectionProfile = CodingKeys(stringValue: "connectionProfile")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "filter",
      "dryRun",
      "autoCommit",
      "connectionProfile",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dryRun) {
      self.dryRun = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .autoCommit) {
      self.autoCommit = value
    }

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let connectionProfile = try container.decodeIfPresent(
      Swift.String.self, forKey: .connectionProfile)
    {
      try destinationCheckAndSet(.connectionProfile(connectionProfile))
    }
    self.destination = destination
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.dryRun, forKey: .dryRun)
    try container.encode(self.autoCommit, forKey: .autoCommit)

    if let choice = self.destination {
      switch choice {
      case .connectionProfile(let value):
        try container.encode(value, forKey: .connectionProfile)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Which destination to use when applying the conversion workspace.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Optional. Fully qualified (Uri) name of the destination connection
    /// profile.
    case connectionProfile(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ApplyConversionWorkspaceRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
