// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for 'ApplyConversionWorkspace' request.
public struct ApplyConversionWorkspaceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the conversion workspace resource for which to apply
  /// the draft tree. Must be in the form of:
  ///  projects/{project}/locations/{location}/conversionWorkspaces/{conversion_workspace}.
  public var name: Swift.String = Swift.String()

  /// Filter which entities to apply. Leaving this field empty will apply all of
  /// the entities. Supports Google AIP 160 based filtering.
  public var filter: Swift.String = Swift.String()

  /// Optional. Only validates the apply process, but doesn't change the
  /// destination database. Only works for PostgreSQL destination connection
  /// profile.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// Optional. Specifies whether the conversion workspace is to be committed
  /// automatically after the apply.
  public var autoCommit: Swift.Bool = Swift.Bool()

  /// Which destination to use when applying the conversion workspace.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `ApplyConversionWorkspaceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApplyConversionWorkspaceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case filter = "filter"
    case dryRun = "dryRun"
    case autoCommit = "autoCommit"
    case connectionProfile = "connectionProfile"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.filter = try container.decode(Swift.String.self, forKey: .filter)
    self.dryRun = try container.decode(Swift.Bool.self, forKey: .dryRun)
    self.autoCommit = try container.decode(Swift.Bool.self, forKey: .autoCommit)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let connectionProfile = try container.decodeIfPresent(
      Swift.String.self, forKey: .connectionProfile)
    {
      try destinationCheckAndSet(.connectionProfile(connectionProfile))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.dryRun, forKey: .dryRun)
    try container.encode(self.autoCommit, forKey: .autoCommit)

    if let choice = self.destination {
      switch choice {
      case .connectionProfile(let value):
        try container.encode(value, forKey: .connectionProfile)
      }
    }
  }

  /// Which destination to use when applying the conversion workspace.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Optional. Fully qualified (Uri) name of the destination connection
    /// profile.
    case connectionProfile(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ApplyConversionWorkspaceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
