// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Execution log of a background job.
public struct BackgroundJobLogEntry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The background job log entry ID.
  public var id: Swift.String = Swift.String()

  /// The type of job that was executed.
  public var jobType: BackgroundJobType = BackgroundJobType()

  /// The timestamp when the background job was started.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// The timestamp when the background job was finished.
  public var finishTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Job completion state, i.e. the final state after the job
  /// completed.
  public var completionState: BackgroundJobLogEntry.JobCompletionState =
    BackgroundJobLogEntry.JobCompletionState()

  /// Output only. Job completion comment, such as how many entities were seeded,
  /// how many warnings were found during conversion, and similar information.
  public var completionComment: Swift.String = Swift.String()

  /// Output only. Whether the client requested the conversion workspace to be
  /// committed after a successful completion of the job.
  public var requestAutocommit: Swift.Bool = Swift.Bool()

  public var jobDetails: OneOf_JobDetails? = nil

  /// Initialize a new instance of `BackgroundJobLogEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackgroundJobLogEntry().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case id = "id"
    case jobType = "jobType"
    case startTime = "startTime"
    case finishTime = "finishTime"
    case completionState = "completionState"
    case completionComment = "completionComment"
    case requestAutocommit = "requestAutocommit"
    case seedJobDetails = "seedJobDetails"
    case importRulesJobDetails = "importRulesJobDetails"
    case convertJobDetails = "convertJobDetails"
    case applyJobDetails = "applyJobDetails"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.jobType = try container.decode(BackgroundJobType.self, forKey: .jobType)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .startTime)
    self.finishTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .finishTime)
    self.completionState = try container.decode(
      BackgroundJobLogEntry.JobCompletionState.self, forKey: .completionState)
    self.completionComment = try container.decode(Swift.String.self, forKey: .completionComment)
    self.requestAutocommit = try container.decode(Swift.Bool.self, forKey: .requestAutocommit)

    var jobDetails: OneOf_JobDetails? = nil
    let jobDetailsCheckAndSet = {
      if jobDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'jobDetails'"))
      }
      jobDetails = $0
    }
    if let seedJobDetails = try container.decodeIfPresent(
      BackgroundJobLogEntry.SeedJobDetails?.self, forKey: .seedJobDetails)
    {
      try jobDetailsCheckAndSet(.seedJobDetails(seedJobDetails))
    }
    if let importRulesJobDetails = try container.decodeIfPresent(
      BackgroundJobLogEntry.ImportRulesJobDetails?.self, forKey: .importRulesJobDetails)
    {
      try jobDetailsCheckAndSet(.importRulesJobDetails(importRulesJobDetails))
    }
    if let convertJobDetails = try container.decodeIfPresent(
      BackgroundJobLogEntry.ConvertJobDetails?.self, forKey: .convertJobDetails)
    {
      try jobDetailsCheckAndSet(.convertJobDetails(convertJobDetails))
    }
    if let applyJobDetails = try container.decodeIfPresent(
      BackgroundJobLogEntry.ApplyJobDetails?.self, forKey: .applyJobDetails)
    {
      try jobDetailsCheckAndSet(.applyJobDetails(applyJobDetails))
    }
    self.jobDetails = jobDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.jobType, forKey: .jobType)
    try container.encode(self.startTime, forKey: .startTime)
    try container.encode(self.finishTime, forKey: .finishTime)
    try container.encode(self.completionState, forKey: .completionState)
    try container.encode(self.completionComment, forKey: .completionComment)
    try container.encode(self.requestAutocommit, forKey: .requestAutocommit)

    if let choice = self.jobDetails {
      switch choice {
      case .seedJobDetails(let value):
        try container.encode(value, forKey: .seedJobDetails)
      case .importRulesJobDetails(let value):
        try container.encode(value, forKey: .importRulesJobDetails)
      case .convertJobDetails(let value):
        try container.encode(value, forKey: .convertJobDetails)
      case .applyJobDetails(let value):
        try container.encode(value, forKey: .applyJobDetails)
      }
    }
  }

  /// Details regarding a Seed background job.
  public struct SeedJobDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The connection profile which was used for the seed job.
    public var connectionProfile: Swift.String = Swift.String()

    /// Initialize a new instance of `SeedJobDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SeedJobDetails().with { $0.connectionProfile = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.clouddms.v1.BackgroundJobLogEntry.SeedJobDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Details regarding an Import Rules background job.
  public struct ImportRulesJobDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. File names used for the import rules job.
    public var files: [Swift.String] = []

    /// Output only. The requested file format.
    public var fileFormat: ImportRulesFileFormat = ImportRulesFileFormat()

    /// Initialize a new instance of `ImportRulesJobDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportRulesJobDetails().with { $0.files = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.clouddms.v1.BackgroundJobLogEntry.ImportRulesJobDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Details regarding a Convert background job.
  public struct ConvertJobDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. AIP-160 based filter used to specify the entities to convert
    public var filter: Swift.String = Swift.String()

    /// Initialize a new instance of `ConvertJobDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConvertJobDetails().with { $0.filter = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.clouddms.v1.BackgroundJobLogEntry.ConvertJobDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Details regarding an Apply background job.
  public struct ApplyJobDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The connection profile which was used for the apply job.
    public var connectionProfile: Swift.String = Swift.String()

    /// Output only. AIP-160 based filter used to specify the entities to apply
    public var filter: Swift.String = Swift.String()

    /// Initialize a new instance of `ApplyJobDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ApplyJobDetails().with { $0.connectionProfile = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.clouddms.v1.BackgroundJobLogEntry.ApplyJobDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Final state after a job completes.
  public enum JobCompletionState: Codable, Equatable, Sendable {
    /// The status is not specified. This state is used when job is not yet
    /// finished.
    case unspecified
    /// Success.
    case succeeded
    /// Error.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .succeeded: return 1
      case .failed: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "JOB_COMPLETION_STATE_UNSPECIFIED"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JobCompletionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "JOB_COMPLETION_STATE_UNSPECIFIED": self = .unspecified
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JobCompletionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .succeeded
      case 2: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .succeeded: return try container.encode(1)
      case .failed: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_JobDetails: Codable, Equatable, Sendable {
    /// Output only. Seed job details.
    indirect case seedJobDetails(BackgroundJobLogEntry.SeedJobDetails?)
    /// Output only. Import rules job details.
    indirect case importRulesJobDetails(BackgroundJobLogEntry.ImportRulesJobDetails?)
    /// Output only. Convert job details.
    indirect case convertJobDetails(BackgroundJobLogEntry.ConvertJobDetails?)
    /// Output only. Apply job details.
    indirect case applyJobDetails(BackgroundJobLogEntry.ApplyJobDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.BackgroundJobLogEntry"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
