// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies required connection parameters, and, optionally, the parameters
/// required to create a Cloud SQL destination database instance.
public struct CloudSqlConnectionProfile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The Cloud SQL instance ID that this connection profile is
  /// associated with.
  public var cloudSqlId: Swift.String = Swift.String()

  /// Immutable. Metadata used to create the destination Cloud SQL database.
  public var settings: CloudSqlSettings? = nil

  /// Output only. The Cloud SQL database instance's private IP.
  public var privateIp: Swift.String = Swift.String()

  /// Output only. The Cloud SQL database instance's public IP.
  public var publicIp: Swift.String = Swift.String()

  /// Output only. The Cloud SQL database instance's additional (outgoing) public
  /// IP. Used when the Cloud SQL database availability type is REGIONAL (i.e.
  /// multiple zones / highly available).
  public var additionalPublicIp: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudSqlConnectionProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudSqlConnectionProfile().with { $0.cloudSqlId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.CloudSqlConnectionProfile"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
