// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Column is not used as an independent entity, it is retrieved as part of a
/// Table entity.
public struct ColumnEntity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Column name.
  public var name: Swift.String = Swift.String()

  /// Column data type.
  public var dataType: Swift.String = Swift.String()

  /// Charset override - instead of table level charset.
  public var charset: Swift.String = Swift.String()

  /// Collation override - instead of table level collation.
  public var collation: Swift.String = Swift.String()

  /// Column length - e.g. varchar (50).
  public var length: Swift.Int64 = Swift.Int64()

  /// Column precision - when relevant.
  public var precision: Swift.Int32 = Swift.Int32()

  /// Column scale - when relevant.
  public var scale: Swift.Int32 = Swift.Int32()

  /// Column fractional second precision - used for timestamp based datatypes.
  public var fractionalSecondsPrecision: Swift.Int32 = Swift.Int32()

  /// Is the column of array type.
  public var array: Swift.Bool = Swift.Bool()

  /// If the column is array, of which length.
  public var arrayLength: Swift.Int32 = Swift.Int32()

  /// Is the column nullable.
  public var nullable: Swift.Bool = Swift.Bool()

  /// Is the column auto-generated/identity.
  public var autoGenerated: Swift.Bool = Swift.Bool()

  /// Is the column a UDT.
  public var udt: Swift.Bool = Swift.Bool()

  /// Custom engine specific features.
  public var customFeatures: GoogleCloudWkt.Struct? = nil

  /// Specifies the list of values allowed in the column.
  /// Only used for set data type.
  public var setValues: [Swift.String] = []

  /// Comment associated with the column.
  public var comment: Swift.String = Swift.String()

  /// Column order in the table.
  public var ordinalPosition: Swift.Int32 = Swift.Int32()

  /// Default value of the column.
  public var defaultValue: Swift.String = Swift.String()

  /// Initialize a new instance of `ColumnEntity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ColumnEntity().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ColumnEntity"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
