// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Column is not used as an independent entity, it is retrieved as part of a
/// Table entity.
public struct ColumnEntity: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Column name.
  public var name: Swift.String = Swift.String()

  /// Column data type.
  public var dataType: Swift.String = Swift.String()

  /// Charset override - instead of table level charset.
  public var charset: Swift.String = Swift.String()

  /// Collation override - instead of table level collation.
  public var collation: Swift.String = Swift.String()

  /// Column length - e.g. varchar (50).
  public var length: Swift.Int64 = Swift.Int64()

  /// Column precision - when relevant.
  public var precision: Swift.Int32 = Swift.Int32()

  /// Column scale - when relevant.
  public var scale: Swift.Int32 = Swift.Int32()

  /// Column fractional second precision - used for timestamp based datatypes.
  public var fractionalSecondsPrecision: Swift.Int32 = Swift.Int32()

  /// Is the column of array type.
  public var array: Swift.Bool = Swift.Bool()

  /// If the column is array, of which length.
  public var arrayLength: Swift.Int32 = Swift.Int32()

  /// Is the column nullable.
  public var nullable: Swift.Bool = Swift.Bool()

  /// Is the column auto-generated/identity.
  public var autoGenerated: Swift.Bool = Swift.Bool()

  /// Is the column a UDT.
  public var udt: Swift.Bool = Swift.Bool()

  /// Custom engine specific features.
  public var customFeatures: GoogleWKT.Struct? = nil

  /// Specifies the list of values allowed in the column.
  /// Only used for set data type.
  public var setValues: [Swift.String] = []

  /// Comment associated with the column.
  public var comment: Swift.String = Swift.String()

  /// Column order in the table.
  public var ordinalPosition: Swift.Int32 = Swift.Int32()

  /// Default value of the column.
  public var defaultValue: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ColumnEntity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ColumnEntity().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let dataType = CodingKeys(stringValue: "dataType")
    static let charset = CodingKeys(stringValue: "charset")
    static let collation = CodingKeys(stringValue: "collation")
    static let length = CodingKeys(stringValue: "length")
    static let precision = CodingKeys(stringValue: "precision")
    static let scale = CodingKeys(stringValue: "scale")
    static let fractionalSecondsPrecision = CodingKeys(stringValue: "fractionalSecondsPrecision")
    static let array = CodingKeys(stringValue: "array")
    static let arrayLength = CodingKeys(stringValue: "arrayLength")
    static let nullable = CodingKeys(stringValue: "nullable")
    static let autoGenerated = CodingKeys(stringValue: "autoGenerated")
    static let udt = CodingKeys(stringValue: "udt")
    static let customFeatures = CodingKeys(stringValue: "customFeatures")
    static let setValues = CodingKeys(stringValue: "setValues")
    static let comment = CodingKeys(stringValue: "comment")
    static let ordinalPosition = CodingKeys(stringValue: "ordinalPosition")
    static let defaultValue = CodingKeys(stringValue: "defaultValue")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "dataType",
      "charset",
      "collation",
      "length",
      "precision",
      "scale",
      "fractionalSecondsPrecision",
      "array",
      "arrayLength",
      "nullable",
      "autoGenerated",
      "udt",
      "customFeatures",
      "setValues",
      "comment",
      "ordinalPosition",
      "defaultValue",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataType) {
      self.dataType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .charset) {
      self.charset = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .collation) {
      self.collation = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .length) {
      self.length = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .precision) {
      self.precision = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .scale) {
      self.scale = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .fractionalSecondsPrecision)
    {
      self.fractionalSecondsPrecision = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .array) {
      self.array = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .arrayLength) {
      self.arrayLength = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .nullable) {
      self.nullable = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .autoGenerated) {
      self.autoGenerated = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .udt) {
      self.udt = value
    }
    self.customFeatures = try container.decodeIfPresent(
      GoogleWKT.Struct.self, forKey: .customFeatures)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .setValues) {
      self.setValues = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .comment) {
      self.comment = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .ordinalPosition) {
      self.ordinalPosition = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultValue) {
      self.defaultValue = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.dataType, forKey: .dataType)
    try container.encode(self.charset, forKey: .charset)
    try container.encode(self.collation, forKey: .collation)
    try container.encode(self.length, forKey: .length)
    try container.encode(self.precision, forKey: .precision)
    try container.encode(self.scale, forKey: .scale)
    try container.encode(self.fractionalSecondsPrecision, forKey: .fractionalSecondsPrecision)
    try container.encode(self.array, forKey: .array)
    try container.encode(self.arrayLength, forKey: .arrayLength)
    try container.encode(self.nullable, forKey: .nullable)
    try container.encode(self.autoGenerated, forKey: .autoGenerated)
    try container.encode(self.udt, forKey: .udt)
    try container.encodeIfPresent(self.customFeatures, forKey: .customFeatures)
    try container.encode(self.setValues, forKey: .setValues)
    try container.encode(self.comment, forKey: .comment)
    try container.encode(self.ordinalPosition, forKey: .ordinalPosition)
    try container.encode(self.defaultValue, forKey: .defaultValue)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ColumnEntity"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
