// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Constraint is not used as an independent entity, it is retrieved
/// as part of another entity such as Table or View.
public struct ConstraintEntity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the table constraint.
  public var name: Swift.String = Swift.String()

  /// Type of constraint, for example unique, primary key, foreign key (currently
  /// only primary key is supported).
  public var type: Swift.String = Swift.String()

  /// Table columns used as part of the Constraint, for example primary key
  /// constraint should list the columns which constitutes the key.
  public var tableColumns: [Swift.String] = []

  /// Custom engine specific features.
  public var customFeatures: GoogleCloudWKT.Struct? = nil

  /// Reference columns which may be associated with the constraint. For example,
  /// if the constraint is a FOREIGN_KEY, this represents the list of full names
  /// of referenced columns by the foreign key.
  public var referenceColumns: [Swift.String] = []

  /// Reference table which may be associated with the constraint. For example,
  /// if the constraint is a FOREIGN_KEY, this represents the list of full name
  /// of the referenced table by the foreign key.
  public var referenceTable: Swift.String = Swift.String()

  /// Table which is associated with the constraint. In case the constraint
  /// is defined on a table, this field is left empty as this information is
  /// stored in parent_name. However, if constraint is defined on a view, this
  /// field stores the table name on which the view is defined.
  public var tableName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConstraintEntity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConstraintEntity().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let type = CodingKeys(stringValue: "type")
    static let tableColumns = CodingKeys(stringValue: "tableColumns")
    static let customFeatures = CodingKeys(stringValue: "customFeatures")
    static let referenceColumns = CodingKeys(stringValue: "referenceColumns")
    static let referenceTable = CodingKeys(stringValue: "referenceTable")
    static let tableName = CodingKeys(stringValue: "tableName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "type",
      "tableColumns",
      "customFeatures",
      "referenceColumns",
      "referenceTable",
      "tableName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tableColumns) {
      self.tableColumns = value
    }
    self.customFeatures = try container.decodeIfPresent(
      GoogleCloudWKT.Struct.self, forKey: .customFeatures)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .referenceColumns) {
      self.referenceColumns = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .referenceTable) {
      self.referenceTable = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tableName) {
      self.tableName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.tableColumns, forKey: .tableColumns)
    try container.encodeIfPresent(self.customFeatures, forKey: .customFeatures)
    try container.encode(self.referenceColumns, forKey: .referenceColumns)
    try container.encode(self.referenceTable, forKey: .referenceTable)
    try container.encode(self.tableName, forKey: .tableName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ConstraintEntity"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
