// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The main conversion workspace resource entity.
public struct ConversionWorkspace: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Full name of the workspace resource, in the form of:
  /// projects/{project}/locations/{location}/conversionWorkspaces/{conversion_workspace}.
  public var name: Swift.String = Swift.String()

  /// Required. The source engine details.
  public var source: DatabaseEngineInfo? = nil

  /// Required. The destination engine details.
  public var destination: DatabaseEngineInfo? = nil

  /// Optional. A generic list of settings for the workspace.
  /// The settings are database pair dependant and can indicate default behavior
  /// for the mapping rules engine or turn on or off specific features.
  /// Such examples can be: convert_foreign_key_to_interleave=true,
  /// skip_triggers=false, ignore_non_table_synonyms=true
  public var globalSettings: [Swift.String: Swift.String] = [:]

  /// Output only. Whether the workspace has uncommitted changes (changes which
  /// were made after the workspace was committed).
  public var hasUncommittedChanges: Swift.Bool = Swift.Bool()

  /// Output only. The latest commit ID.
  public var latestCommitId: Swift.String = Swift.String()

  /// Output only. The timestamp when the workspace was committed.
  public var latestCommitTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when the workspace resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when the workspace resource was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The display name for the workspace.
  public var displayName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConversionWorkspace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConversionWorkspace().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let source = CodingKeys(stringValue: "source")
    static let destination = CodingKeys(stringValue: "destination")
    static let globalSettings = CodingKeys(stringValue: "globalSettings")
    static let hasUncommittedChanges = CodingKeys(stringValue: "hasUncommittedChanges")
    static let latestCommitId = CodingKeys(stringValue: "latestCommitId")
    static let latestCommitTime = CodingKeys(stringValue: "latestCommitTime")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let displayName = CodingKeys(stringValue: "displayName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "source",
      "destination",
      "globalSettings",
      "hasUncommittedChanges",
      "latestCommitId",
      "latestCommitTime",
      "createTime",
      "updateTime",
      "displayName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.source = try container.decodeIfPresent(DatabaseEngineInfo.self, forKey: .source)
    self.destination = try container.decodeIfPresent(DatabaseEngineInfo.self, forKey: .destination)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .globalSettings)
    {
      self.globalSettings = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hasUncommittedChanges) {
      self.hasUncommittedChanges = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .latestCommitId) {
      self.latestCommitId = value
    }
    self.latestCommitTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .latestCommitTime)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.source, forKey: .source)
    try container.encodeIfPresent(self.destination, forKey: .destination)
    try container.encode(self.globalSettings, forKey: .globalSettings)
    try container.encode(self.hasUncommittedChanges, forKey: .hasUncommittedChanges)
    try container.encode(self.latestCommitId, forKey: .latestCommitId)
    try container.encodeIfPresent(self.latestCommitTime, forKey: .latestCommitTime)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.displayName, forKey: .displayName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ConversionWorkspace"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
