// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for 'ConvertConversionWorkspace' request.
public struct ConvertConversionWorkspaceRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Name of the conversion workspace resource to convert in the form of:
  /// projects/{project}/locations/{location}/conversionWorkspaces/{conversion_workspace}.
  public var name: Swift.String = Swift.String()

  /// Optional. Specifies whether the conversion workspace is to be committed
  /// automatically after the conversion.
  public var autoCommit: Swift.Bool = Swift.Bool()

  /// Optional. Filter the entities to convert. Leaving this field empty will
  /// convert all of the entities. Supports Google AIP-160 style filtering.
  public var filter: Swift.String = Swift.String()

  /// Optional. Automatically convert the full entity path for each entity
  /// specified by the filter. For example, if the filter specifies a table, that
  /// table schema (and database if there is one) will also be converted.
  public var convertFullPath: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ConvertConversionWorkspaceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConvertConversionWorkspaceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ConvertConversionWorkspaceRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
