// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message to create a new private connection in the specified project
/// and region.
public struct CreatePrivateConnectionRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent that owns the collection of PrivateConnections.
  public var parent: Swift.String = Swift.String()

  /// Required. The private connection identifier.
  public var privateConnectionId: Swift.String = Swift.String()

  /// Required. The private connection resource to create.
  public var privateConnection: PrivateConnection? = nil

  /// Optional. A unique ID used to identify the request. If the server receives
  /// two requests with the same ID, then the second request is ignored.
  ///
  /// It is recommended to always set this value to a UUID.
  ///
  /// The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores
  /// (_), and hyphens (-). The maximum length is 40 characters.
  public var requestId: Swift.String = Swift.String()

  /// Optional. If set to true, will skip validations.
  public var skipValidation: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreatePrivateConnectionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreatePrivateConnectionRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.CreatePrivateConnectionRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
