// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The base entity type for all the database related entities.
/// The message contains the entity name, the name of its parent, the entity
/// type, and the specific details per entity type.
public struct DatabaseEntity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The short name (e.g. table name) of the entity.
  public var shortName: Swift.String = Swift.String()

  /// The full name of the parent entity (e.g. schema name).
  public var parentEntity: Swift.String = Swift.String()

  /// The type of tree the entity belongs to.
  public var tree: DatabaseEntity.TreeType = DatabaseEntity.TreeType()

  /// The type of the database entity (table, view, index, ...).
  public var entityType: DatabaseEntityType = DatabaseEntityType()

  /// Details about entity mappings.
  /// For source tree entities, this holds the draft entities which were
  /// generated by the mapping rules.
  /// For draft tree entities, this holds the source entities which were
  /// converted to form the draft entity.
  /// Destination entities will have no mapping details.
  public var mappings: [EntityMapping] = []

  /// Details about the entity DDL script. Multiple DDL scripts are provided for
  /// child entities such as a table entity will have one DDL for the table with
  /// additional DDLs for each index, constraint and such.
  public var entityDdl: [EntityDdl] = []

  /// Details about the various issues found for the entity.
  public var issues: [EntityIssue] = []

  /// The specific body for each entity type.
  public var entityBody: OneOf_EntityBody? = nil

  /// Initialize a new instance of `DatabaseEntity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatabaseEntity().with { $0.shortName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case shortName = "shortName"
    case parentEntity = "parentEntity"
    case tree = "tree"
    case entityType = "entityType"
    case mappings = "mappings"
    case entityDdl = "entityDdl"
    case issues = "issues"
    case database = "database"
    case schema = "schema"
    case table = "table"
    case view = "view"
    case sequence = "sequence"
    case storedProcedure = "storedProcedure"
    case databaseFunction = "databaseFunction"
    case synonym = "synonym"
    case databasePackage = "databasePackage"
    case udt = "udt"
    case materializedView = "materializedView"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.shortName = try container.decode(Swift.String.self, forKey: .shortName)
    self.parentEntity = try container.decode(Swift.String.self, forKey: .parentEntity)
    self.tree = try container.decode(DatabaseEntity.TreeType.self, forKey: .tree)
    self.entityType = try container.decode(DatabaseEntityType.self, forKey: .entityType)
    self.mappings = try container.decode([EntityMapping].self, forKey: .mappings)
    self.entityDdl = try container.decode([EntityDdl].self, forKey: .entityDdl)
    self.issues = try container.decode([EntityIssue].self, forKey: .issues)

    var entityBody: OneOf_EntityBody? = nil
    let entityBodyCheckAndSet = {
      if entityBody != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'entityBody'"))
      }
      entityBody = $0
    }
    if let database = try container.decodeIfPresent(DatabaseInstanceEntity?.self, forKey: .database)
    {
      try entityBodyCheckAndSet(.database(database))
    }
    if let schema = try container.decodeIfPresent(SchemaEntity?.self, forKey: .schema) {
      try entityBodyCheckAndSet(.schema(schema))
    }
    if let table = try container.decodeIfPresent(TableEntity?.self, forKey: .table) {
      try entityBodyCheckAndSet(.table(table))
    }
    if let view = try container.decodeIfPresent(ViewEntity?.self, forKey: .view) {
      try entityBodyCheckAndSet(.view(view))
    }
    if let sequence = try container.decodeIfPresent(SequenceEntity?.self, forKey: .sequence) {
      try entityBodyCheckAndSet(.sequence(sequence))
    }
    if let storedProcedure = try container.decodeIfPresent(
      StoredProcedureEntity?.self, forKey: .storedProcedure)
    {
      try entityBodyCheckAndSet(.storedProcedure(storedProcedure))
    }
    if let databaseFunction = try container.decodeIfPresent(
      FunctionEntity?.self, forKey: .databaseFunction)
    {
      try entityBodyCheckAndSet(.databaseFunction(databaseFunction))
    }
    if let synonym = try container.decodeIfPresent(SynonymEntity?.self, forKey: .synonym) {
      try entityBodyCheckAndSet(.synonym(synonym))
    }
    if let databasePackage = try container.decodeIfPresent(
      PackageEntity?.self, forKey: .databasePackage)
    {
      try entityBodyCheckAndSet(.databasePackage(databasePackage))
    }
    if let udt = try container.decodeIfPresent(UDTEntity?.self, forKey: .udt) {
      try entityBodyCheckAndSet(.udt(udt))
    }
    if let materializedView = try container.decodeIfPresent(
      MaterializedViewEntity?.self, forKey: .materializedView)
    {
      try entityBodyCheckAndSet(.materializedView(materializedView))
    }
    self.entityBody = entityBody
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.shortName, forKey: .shortName)
    try container.encode(self.parentEntity, forKey: .parentEntity)
    try container.encode(self.tree, forKey: .tree)
    try container.encode(self.entityType, forKey: .entityType)
    try container.encode(self.mappings, forKey: .mappings)
    try container.encode(self.entityDdl, forKey: .entityDdl)
    try container.encode(self.issues, forKey: .issues)

    if let choice = self.entityBody {
      switch choice {
      case .database(let value):
        try container.encode(value, forKey: .database)
      case .schema(let value):
        try container.encode(value, forKey: .schema)
      case .table(let value):
        try container.encode(value, forKey: .table)
      case .view(let value):
        try container.encode(value, forKey: .view)
      case .sequence(let value):
        try container.encode(value, forKey: .sequence)
      case .storedProcedure(let value):
        try container.encode(value, forKey: .storedProcedure)
      case .databaseFunction(let value):
        try container.encode(value, forKey: .databaseFunction)
      case .synonym(let value):
        try container.encode(value, forKey: .synonym)
      case .databasePackage(let value):
        try container.encode(value, forKey: .databasePackage)
      case .udt(let value):
        try container.encode(value, forKey: .udt)
      case .materializedView(let value):
        try container.encode(value, forKey: .materializedView)
      }
    }
  }

  /// The type of database entities tree.
  public enum TreeType: Codable, Equatable, Sendable {
    /// Tree type unspecified.
    case unspecified
    /// Tree of entities loaded from a source database.
    case source
    /// Tree of entities converted from the source tree using the mapping rules.
    case draft
    /// Tree of entities observed on the destination database.
    case destination
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .source: return 1
      case .draft: return 2
      case .destination: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TREE_TYPE_UNSPECIFIED"
      case .source: return "SOURCE"
      case .draft: return "DRAFT"
      case .destination: return "DESTINATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TreeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TREE_TYPE_UNSPECIFIED": self = .unspecified
      case "SOURCE": self = .source
      case "DRAFT": self = .draft
      case "DESTINATION": self = .destination
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TreeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .source
      case 2: self = .draft
      case 3: self = .destination
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .source: return try container.encode(1)
      case .draft: return try container.encode(2)
      case .destination: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The specific body for each entity type.
  public enum OneOf_EntityBody: Codable, Equatable, Sendable {
    /// Database.
    indirect case database(DatabaseInstanceEntity?)
    /// Schema.
    indirect case schema(SchemaEntity?)
    /// Table.
    indirect case table(TableEntity?)
    /// View.
    indirect case view(ViewEntity?)
    /// Sequence.
    indirect case sequence(SequenceEntity?)
    /// Stored procedure.
    indirect case storedProcedure(StoredProcedureEntity?)
    /// Function.
    indirect case databaseFunction(FunctionEntity?)
    /// Synonym.
    indirect case synonym(SynonymEntity?)
    /// Package.
    indirect case databasePackage(PackageEntity?)
    /// UDT.
    indirect case udt(UDTEntity?)
    /// Materialized view.
    indirect case materializedView(MaterializedViewEntity?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.DatabaseEntity"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
