// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class DataMigrationServiceLogging: DataMigrationServiceStub {
    let inner: any DataMigrationServiceStub
    let logger: Logger

    public init(_ inner: any DataMigrationServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-clouddms-v1"
      logger[metadataKey: "gcp.client.service"] = "datamigration"
      logger[metadataKey: "gcp.experimental.swift.client"] = "DataMigrationService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listMigrationJobs(
      request: ListMigrationJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListMigrationJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMigrationJobs",
        action: {
          (r: ListMigrationJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListMigrationJobsResponse
          in
          return try await self.inner.listMigrationJobs(request: r, options: o)
        })
    }

    public func getMigrationJob(
      request: GetMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MigrationJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMigrationJob",
        action: {
          (r: GetMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.MigrationJob
          in
          return try await self.inner.getMigrationJob(request: r, options: o)
        })
    }

    public func createMigrationJob(
      request: CreateMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMigrationJob",
        action: {
          (r: CreateMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMigrationJob(request: r, options: o)
        })
    }

    public func updateMigrationJob(
      request: UpdateMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateMigrationJob",
        action: {
          (r: UpdateMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMigrationJob(request: r, options: o)
        })
    }

    public func deleteMigrationJob(
      request: DeleteMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteMigrationJob",
        action: {
          (r: DeleteMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMigrationJob(request: r, options: o)
        })
    }

    public func startMigrationJob(
      request: StartMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "startMigrationJob",
        action: {
          (r: StartMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startMigrationJob(request: r, options: o)
        })
    }

    public func stopMigrationJob(
      request: StopMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "stopMigrationJob",
        action: {
          (r: StopMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopMigrationJob(request: r, options: o)
        })
    }

    public func resumeMigrationJob(
      request: ResumeMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumeMigrationJob",
        action: {
          (r: ResumeMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resumeMigrationJob(request: r, options: o)
        })
    }

    public func promoteMigrationJob(
      request: PromoteMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "promoteMigrationJob",
        action: {
          (r: PromoteMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.promoteMigrationJob(request: r, options: o)
        })
    }

    public func verifyMigrationJob(
      request: VerifyMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "verifyMigrationJob",
        action: {
          (r: VerifyMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.verifyMigrationJob(request: r, options: o)
        })
    }

    public func restartMigrationJob(
      request: RestartMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "restartMigrationJob",
        action: {
          (r: RestartMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restartMigrationJob(request: r, options: o)
        })
    }

    public func generateSshScript(
      request: GenerateSshScriptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.SshScript {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateSshScript",
        action: {
          (r: GenerateSshScriptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.SshScript
          in
          return try await self.inner.generateSshScript(request: r, options: o)
        })
    }

    public func generateTcpProxyScript(
      request: GenerateTcpProxyScriptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.TcpProxyScript {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateTcpProxyScript",
        action: {
          (r: GenerateTcpProxyScriptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.TcpProxyScript
          in
          return try await self.inner.generateTcpProxyScript(request: r, options: o)
        })
    }

    public func listConnectionProfiles(
      request: ListConnectionProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListConnectionProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnectionProfiles",
        action: {
          (r: ListConnectionProfilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListConnectionProfilesResponse
          in
          return try await self.inner.listConnectionProfiles(request: r, options: o)
        })
    }

    public func getConnectionProfile(
      request: GetConnectionProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ConnectionProfile {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnectionProfile",
        action: {
          (r: GetConnectionProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ConnectionProfile
          in
          return try await self.inner.getConnectionProfile(request: r, options: o)
        })
    }

    public func createConnectionProfile(
      request: CreateConnectionProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConnectionProfile",
        action: {
          (r: CreateConnectionProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConnectionProfile(request: r, options: o)
        })
    }

    public func updateConnectionProfile(
      request: UpdateConnectionProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConnectionProfile",
        action: {
          (r: UpdateConnectionProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConnectionProfile(request: r, options: o)
        })
    }

    public func deleteConnectionProfile(
      request: DeleteConnectionProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConnectionProfile",
        action: {
          (r: DeleteConnectionProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConnectionProfile(request: r, options: o)
        })
    }

    public func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPrivateConnection",
        action: {
          (r: CreatePrivateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPrivateConnection(request: r, options: o)
        })
    }

    public func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.PrivateConnection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPrivateConnection",
        action: {
          (r: GetPrivateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.PrivateConnection
          in
          return try await self.inner.getPrivateConnection(request: r, options: o)
        })
    }

    public func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListPrivateConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPrivateConnections",
        action: {
          (r: ListPrivateConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListPrivateConnectionsResponse
          in
          return try await self.inner.listPrivateConnections(request: r, options: o)
        })
    }

    public func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePrivateConnection",
        action: {
          (r: DeletePrivateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePrivateConnection(request: r, options: o)
        })
    }

    public func getConversionWorkspace(
      request: GetConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ConversionWorkspace {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConversionWorkspace",
        action: {
          (r: GetConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ConversionWorkspace
          in
          return try await self.inner.getConversionWorkspace(request: r, options: o)
        })
    }

    public func listConversionWorkspaces(
      request: ListConversionWorkspacesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListConversionWorkspacesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConversionWorkspaces",
        action: {
          (r: ListConversionWorkspacesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListConversionWorkspacesResponse
          in
          return try await self.inner.listConversionWorkspaces(request: r, options: o)
        })
    }

    public func createConversionWorkspace(
      request: CreateConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConversionWorkspace",
        action: {
          (r: CreateConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConversionWorkspace(request: r, options: o)
        })
    }

    public func updateConversionWorkspace(
      request: UpdateConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConversionWorkspace",
        action: {
          (r: UpdateConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConversionWorkspace(request: r, options: o)
        })
    }

    public func deleteConversionWorkspace(
      request: DeleteConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConversionWorkspace",
        action: {
          (r: DeleteConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConversionWorkspace(request: r, options: o)
        })
    }

    public func createMappingRule(
      request: CreateMappingRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MappingRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMappingRule",
        action: {
          (r: CreateMappingRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.MappingRule
          in
          return try await self.inner.createMappingRule(request: r, options: o)
        })
    }

    public func deleteMappingRule(
      request: DeleteMappingRuleRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteMappingRule",
        action: { (r: DeleteMappingRuleRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteMappingRule(request: r, options: o)
        })
    }

    public func listMappingRules(
      request: ListMappingRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListMappingRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMappingRules",
        action: {
          (r: ListMappingRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListMappingRulesResponse
          in
          return try await self.inner.listMappingRules(request: r, options: o)
        })
    }

    public func getMappingRule(
      request: GetMappingRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MappingRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMappingRule",
        action: {
          (r: GetMappingRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.MappingRule
          in
          return try await self.inner.getMappingRule(request: r, options: o)
        })
    }

    public func seedConversionWorkspace(
      request: SeedConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "seedConversionWorkspace",
        action: {
          (r: SeedConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.seedConversionWorkspace(request: r, options: o)
        })
    }

    public func importMappingRules(
      request: ImportMappingRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importMappingRules",
        action: {
          (r: ImportMappingRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importMappingRules(request: r, options: o)
        })
    }

    public func convertConversionWorkspace(
      request: ConvertConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "convertConversionWorkspace",
        action: {
          (r: ConvertConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.convertConversionWorkspace(request: r, options: o)
        })
    }

    public func commitConversionWorkspace(
      request: CommitConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "commitConversionWorkspace",
        action: {
          (r: CommitConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.commitConversionWorkspace(request: r, options: o)
        })
    }

    public func rollbackConversionWorkspace(
      request: RollbackConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "rollbackConversionWorkspace",
        action: {
          (r: RollbackConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.rollbackConversionWorkspace(request: r, options: o)
        })
    }

    public func applyConversionWorkspace(
      request: ApplyConversionWorkspaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "applyConversionWorkspace",
        action: {
          (r: ApplyConversionWorkspaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.applyConversionWorkspace(request: r, options: o)
        })
    }

    public func describeDatabaseEntities(
      request: DescribeDatabaseEntitiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.DescribeDatabaseEntitiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "describeDatabaseEntities",
        action: {
          (r: DescribeDatabaseEntitiesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.DescribeDatabaseEntitiesResponse
          in
          return try await self.inner.describeDatabaseEntities(request: r, options: o)
        })
    }

    public func searchBackgroundJobs(
      request: SearchBackgroundJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.SearchBackgroundJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchBackgroundJobs",
        action: {
          (r: SearchBackgroundJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.SearchBackgroundJobsResponse
          in
          return try await self.inner.searchBackgroundJobs(request: r, options: o)
        })
    }

    public func describeConversionWorkspaceRevisions(
      request: DescribeConversionWorkspaceRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.DescribeConversionWorkspaceRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "describeConversionWorkspaceRevisions",
        action: {
          (r: DescribeConversionWorkspaceRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.DescribeConversionWorkspaceRevisionsResponse
          in
          return try await self.inner.describeConversionWorkspaceRevisions(request: r, options: o)
        })
    }

    public func fetchStaticIps(
      request: FetchStaticIpsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.FetchStaticIpsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchStaticIps",
        action: {
          (r: FetchStaticIpsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.FetchStaticIpsResponse
          in
          return try await self.inner.fetchStaticIps(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
