// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class DataMigrationServiceRetry: DataMigrationServiceStub {
    let inner: any DataMigrationServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any DataMigrationServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listMigrationJobs(
      request: ListMigrationJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListMigrationJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMigrationJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListMigrationJobsResponse
          in
          return try await self.inner.listMigrationJobs(request: r, options: o)
        })
    }

    public func getMigrationJob(
      request: GetMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MigrationJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.MigrationJob
          in
          return try await self.inner.getMigrationJob(request: r, options: o)
        })
    }

    public func createMigrationJob(
      request: CreateMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMigrationJob(request: r, options: o)
        })
    }

    public func updateMigrationJob(
      request: UpdateMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMigrationJob(request: r, options: o)
        })
    }

    public func deleteMigrationJob(
      request: DeleteMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMigrationJob(request: r, options: o)
        })
    }

    public func startMigrationJob(
      request: StartMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StartMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startMigrationJob(request: r, options: o)
        })
    }

    public func stopMigrationJob(
      request: StopMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.stopMigrationJob(request: r, options: o)
        })
    }

    public func resumeMigrationJob(
      request: ResumeMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResumeMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resumeMigrationJob(request: r, options: o)
        })
    }

    public func promoteMigrationJob(
      request: PromoteMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PromoteMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.promoteMigrationJob(request: r, options: o)
        })
    }

    public func verifyMigrationJob(
      request: VerifyMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: VerifyMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.verifyMigrationJob(request: r, options: o)
        })
    }

    public func restartMigrationJob(
      request: RestartMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RestartMigrationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restartMigrationJob(request: r, options: o)
        })
    }

    public func generateSshScript(
      request: GenerateSshScriptRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.SshScript {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateSshScriptRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.SshScript
          in
          return try await self.inner.generateSshScript(request: r, options: o)
        })
    }

    public func generateTcpProxyScript(
      request: GenerateTcpProxyScriptRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.TcpProxyScript {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateTcpProxyScriptRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.TcpProxyScript
          in
          return try await self.inner.generateTcpProxyScript(request: r, options: o)
        })
    }

    public func listConnectionProfiles(
      request: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListConnectionProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListConnectionProfilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListConnectionProfilesResponse
          in
          return try await self.inner.listConnectionProfiles(request: r, options: o)
        })
    }

    public func getConnectionProfile(
      request: GetConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ConnectionProfile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetConnectionProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ConnectionProfile
          in
          return try await self.inner.getConnectionProfile(request: r, options: o)
        })
    }

    public func createConnectionProfile(
      request: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateConnectionProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConnectionProfile(request: r, options: o)
        })
    }

    public func updateConnectionProfile(
      request: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateConnectionProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConnectionProfile(request: r, options: o)
        })
    }

    public func deleteConnectionProfile(
      request: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteConnectionProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConnectionProfile(request: r, options: o)
        })
    }

    public func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePrivateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPrivateConnection(request: r, options: o)
        })
    }

    public func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.PrivateConnection {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPrivateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.PrivateConnection
          in
          return try await self.inner.getPrivateConnection(request: r, options: o)
        })
    }

    public func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListPrivateConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPrivateConnectionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListPrivateConnectionsResponse
          in
          return try await self.inner.listPrivateConnections(request: r, options: o)
        })
    }

    public func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePrivateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePrivateConnection(request: r, options: o)
        })
    }

    public func getConversionWorkspace(
      request: GetConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ConversionWorkspace {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ConversionWorkspace
          in
          return try await self.inner.getConversionWorkspace(request: r, options: o)
        })
    }

    public func listConversionWorkspaces(
      request: ListConversionWorkspacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListConversionWorkspacesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListConversionWorkspacesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListConversionWorkspacesResponse
          in
          return try await self.inner.listConversionWorkspaces(request: r, options: o)
        })
    }

    public func createConversionWorkspace(
      request: CreateConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConversionWorkspace(request: r, options: o)
        })
    }

    public func updateConversionWorkspace(
      request: UpdateConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConversionWorkspace(request: r, options: o)
        })
    }

    public func deleteConversionWorkspace(
      request: DeleteConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConversionWorkspace(request: r, options: o)
        })
    }

    public func createMappingRule(
      request: CreateMappingRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MappingRule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMappingRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.MappingRule
          in
          return try await self.inner.createMappingRule(request: r, options: o)
        })
    }

    public func deleteMappingRule(
      request: DeleteMappingRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMappingRuleRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteMappingRule(request: r, options: o)
        })
    }

    public func listMappingRules(
      request: ListMappingRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListMappingRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMappingRulesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.ListMappingRulesResponse
          in
          return try await self.inner.listMappingRules(request: r, options: o)
        })
    }

    public func getMappingRule(
      request: GetMappingRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MappingRule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMappingRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.MappingRule
          in
          return try await self.inner.getMappingRule(request: r, options: o)
        })
    }

    public func seedConversionWorkspace(
      request: SeedConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SeedConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.seedConversionWorkspace(request: r, options: o)
        })
    }

    public func importMappingRules(
      request: ImportMappingRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ImportMappingRulesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importMappingRules(request: r, options: o)
        })
    }

    public func convertConversionWorkspace(
      request: ConvertConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ConvertConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.convertConversionWorkspace(request: r, options: o)
        })
    }

    public func commitConversionWorkspace(
      request: CommitConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CommitConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.commitConversionWorkspace(request: r, options: o)
        })
    }

    public func rollbackConversionWorkspace(
      request: RollbackConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RollbackConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.rollbackConversionWorkspace(request: r, options: o)
        })
    }

    public func applyConversionWorkspace(
      request: ApplyConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ApplyConversionWorkspaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.applyConversionWorkspace(request: r, options: o)
        })
    }

    public func describeDatabaseEntities(
      request: DescribeDatabaseEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.DescribeDatabaseEntitiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: DescribeDatabaseEntitiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.DescribeDatabaseEntitiesResponse
          in
          return try await self.inner.describeDatabaseEntities(request: r, options: o)
        })
    }

    public func searchBackgroundJobs(
      request: SearchBackgroundJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.SearchBackgroundJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchBackgroundJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.SearchBackgroundJobsResponse
          in
          return try await self.inner.searchBackgroundJobs(request: r, options: o)
        })
    }

    public func describeConversionWorkspaceRevisions(
      request: DescribeConversionWorkspaceRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.DescribeConversionWorkspaceRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: DescribeConversionWorkspaceRevisionsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudDMSV1.DescribeConversionWorkspaceRevisionsResponse
          in
          return try await self.inner.describeConversionWorkspaceRevisions(request: r, options: o)
        })
    }

    public func fetchStaticIps(
      request: FetchStaticIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.FetchStaticIpsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchStaticIpsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDMSV1.FetchStaticIpsResponse
          in
          return try await self.inner.fetchStaticIps(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
