// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// AIP-157 Partial Response view for Database Entity.
public enum DatabaseEntityView: Codable, Equatable, Sendable {
  /// Unspecified view. Defaults to basic view.
  case unspecified
  /// Default view. Does not return DDLs or Issues.
  case basic
  /// Return full entity details including mappings, ddl and issues.
  case full
  /// Top-most (Database, Schema) nodes which are returned contains summary
  /// details for their decendents such as the number of entities per type and
  /// issues rollups. When this view is used, only a single page of result is
  /// returned and the page_size property of the request is ignored. The
  /// returned page will only include the top-most node types.
  case rootSummary
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .basic: return 1
    case .full: return 2
    case .rootSummary: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "DATABASE_ENTITY_VIEW_UNSPECIFIED"
    case .basic: return "DATABASE_ENTITY_VIEW_BASIC"
    case .full: return "DATABASE_ENTITY_VIEW_FULL"
    case .rootSummary: return "DATABASE_ENTITY_VIEW_ROOT_SUMMARY"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DatabaseEntityView/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DATABASE_ENTITY_VIEW_UNSPECIFIED": self = .unspecified
    case "DATABASE_ENTITY_VIEW_BASIC": self = .basic
    case "DATABASE_ENTITY_VIEW_FULL": self = .full
    case "DATABASE_ENTITY_VIEW_ROOT_SUMMARY": self = .rootSummary
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DatabaseEntityView/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .basic
    case 2: self = .full
    case 3: self = .rootSummary
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .basic: return try container.encode(1)
    case .full: return try container.encode(2)
    case .rootSummary: return try container.encode(3)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
