// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol DataMigrationServiceStub {
    func listMigrationJobs(
      request: ListMigrationJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListMigrationJobsResponse

    func getMigrationJob(
      request: GetMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MigrationJob

    func createMigrationJob(
      request: CreateMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMigrationJob(
      request: UpdateMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMigrationJob(
      request: DeleteMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func startMigrationJob(
      request: StartMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func stopMigrationJob(
      request: StopMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func resumeMigrationJob(
      request: ResumeMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func promoteMigrationJob(
      request: PromoteMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func verifyMigrationJob(
      request: VerifyMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func restartMigrationJob(
      request: RestartMigrationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func generateSshScript(
      request: GenerateSshScriptRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.SshScript

    func generateTcpProxyScript(
      request: GenerateTcpProxyScriptRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.TcpProxyScript

    func listConnectionProfiles(
      request: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListConnectionProfilesResponse

    func getConnectionProfile(
      request: GetConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ConnectionProfile

    func createConnectionProfile(
      request: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateConnectionProfile(
      request: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteConnectionProfile(
      request: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.PrivateConnection

    func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListPrivateConnectionsResponse

    func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getConversionWorkspace(
      request: GetConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ConversionWorkspace

    func listConversionWorkspaces(
      request: ListConversionWorkspacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListConversionWorkspacesResponse

    func createConversionWorkspace(
      request: CreateConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateConversionWorkspace(
      request: UpdateConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteConversionWorkspace(
      request: DeleteConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createMappingRule(
      request: CreateMappingRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MappingRule

    func deleteMappingRule(
      request: DeleteMappingRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listMappingRules(
      request: ListMappingRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.ListMappingRulesResponse

    func getMappingRule(
      request: GetMappingRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.MappingRule

    func seedConversionWorkspace(
      request: SeedConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func importMappingRules(
      request: ImportMappingRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func convertConversionWorkspace(
      request: ConvertConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func commitConversionWorkspace(
      request: CommitConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func rollbackConversionWorkspace(
      request: RollbackConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func applyConversionWorkspace(
      request: ApplyConversionWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func describeDatabaseEntities(
      request: DescribeDatabaseEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.DescribeDatabaseEntitiesResponse

    func searchBackgroundJobs(
      request: SearchBackgroundJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.SearchBackgroundJobsResponse

    func describeConversionWorkspaceRevisions(
      request: DescribeConversionWorkspaceRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.DescribeConversionWorkspaceRevisionsResponse

    func fetchStaticIps(
      request: FetchStaticIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDMSV1.FetchStaticIpsResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
