// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Details of the mappings of a database entity.
public struct EntityMapping: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Source entity full name.
  /// The source entity can also be a column, index or constraint using the
  /// same naming notation schema.table.column.
  public var sourceEntity: Swift.String = Swift.String()

  /// Target entity full name.
  /// The draft entity can also include a column, index or constraint using the
  /// same naming notation schema.table.column.
  public var draftEntity: Swift.String = Swift.String()

  /// Type of source entity.
  public var sourceType: DatabaseEntityType = DatabaseEntityType()

  /// Type of draft entity.
  public var draftType: DatabaseEntityType = DatabaseEntityType()

  /// Entity mapping log entries.
  /// Multiple rules can be effective and contribute changes to a converted
  /// entity, such as a rule can handle the entity name, another rule can handle
  /// an entity type. In addition, rules which did not change the entity are also
  /// logged along with the reason preventing them to do so.
  public var mappingLog: [EntityMappingLogEntry] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EntityMapping`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntityMapping().with { $0.sourceEntity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sourceEntity = CodingKeys(stringValue: "sourceEntity")
    static let draftEntity = CodingKeys(stringValue: "draftEntity")
    static let sourceType = CodingKeys(stringValue: "sourceType")
    static let draftType = CodingKeys(stringValue: "draftType")
    static let mappingLog = CodingKeys(stringValue: "mappingLog")

    static let _knownKeys: Set<Swift.String> = [
      "sourceEntity",
      "draftEntity",
      "sourceType",
      "draftType",
      "mappingLog",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceEntity) {
      self.sourceEntity = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .draftEntity) {
      self.draftEntity = value
    }
    if let value = try container.decodeIfPresent(DatabaseEntityType.self, forKey: .sourceType) {
      self.sourceType = value
    }
    if let value = try container.decodeIfPresent(DatabaseEntityType.self, forKey: .draftType) {
      self.draftType = value
    }
    if let value = try container.decodeIfPresent([EntityMappingLogEntry].self, forKey: .mappingLog)
    {
      self.mappingLog = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceEntity, forKey: .sourceEntity)
    try container.encode(self.draftEntity, forKey: .draftEntity)
    try container.encode(self.sourceType, forKey: .sourceType)
    try container.encode(self.draftType, forKey: .draftType)
    try container.encode(self.mappingLog, forKey: .mappingLog)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.EntityMapping"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
