// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details of the mappings of a database entity.
public struct EntityMapping: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Source entity full name.
  /// The source entity can also be a column, index or constraint using the
  /// same naming notation schema.table.column.
  public var sourceEntity: Swift.String = Swift.String()

  /// Target entity full name.
  /// The draft entity can also include a column, index or constraint using the
  /// same naming notation schema.table.column.
  public var draftEntity: Swift.String = Swift.String()

  /// Type of source entity.
  public var sourceType: DatabaseEntityType = DatabaseEntityType()

  /// Type of draft entity.
  public var draftType: DatabaseEntityType = DatabaseEntityType()

  /// Entity mapping log entries.
  /// Multiple rules can be effective and contribute changes to a converted
  /// entity, such as a rule can handle the entity name, another rule can handle
  /// an entity type. In addition, rules which did not change the entity are also
  /// logged along with the reason preventing them to do so.
  public var mappingLog: [EntityMappingLogEntry] = []

  /// Initialize a new instance of `EntityMapping`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntityMapping().with { $0.sourceEntity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.EntityMapping"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
