// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for 'GenerateTcpProxyScript' request.
public struct GenerateTcpProxyScriptRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the migration job resource to generate the TCP Proxy script.
  public var migrationJob: Swift.String = Swift.String()

  /// Required. The name of the Compute instance that will host the proxy.
  public var vmName: Swift.String = Swift.String()

  /// Required. The type of the Compute instance that will host the proxy.
  public var vmMachineType: Swift.String = Swift.String()

  /// Optional. The Google Cloud Platform zone to create the VM in. The fully
  /// qualified name of the zone must be specified, including the region name,
  /// for example "us-central1-b". If not specified, uses the "-b" zone of the
  /// destination Connection Profile's region.
  public var vmZone: Swift.String = Swift.String()

  /// Required. The name of the subnet the Compute instance will use for private
  /// connectivity. Must be supplied in the form of
  /// projects/{project}/regions/{region}/subnetworks/{subnetwork}.
  /// Note: the region for the subnet must match the Compute instance region.
  public var vmSubnet: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GenerateTcpProxyScriptRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateTcpProxyScriptRequest().with { $0.migrationJob = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let migrationJob = CodingKeys(stringValue: "migrationJob")
    static let vmName = CodingKeys(stringValue: "vmName")
    static let vmMachineType = CodingKeys(stringValue: "vmMachineType")
    static let vmZone = CodingKeys(stringValue: "vmZone")
    static let vmSubnet = CodingKeys(stringValue: "vmSubnet")

    static let _knownKeys: Set<Swift.String> = [
      "migrationJob",
      "vmName",
      "vmMachineType",
      "vmZone",
      "vmSubnet",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .migrationJob) {
      self.migrationJob = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmName) {
      self.vmName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmMachineType) {
      self.vmMachineType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmZone) {
      self.vmZone = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmSubnet) {
      self.vmSubnet = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.migrationJob, forKey: .migrationJob)
    try container.encode(self.vmName, forKey: .vmName)
    try container.encode(self.vmMachineType, forKey: .vmMachineType)
    try container.encode(self.vmZone, forKey: .vmZone)
    try container.encode(self.vmSubnet, forKey: .vmSubnet)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.GenerateTcpProxyScriptRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
