// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message to retrieve a list of private connections in a given project
/// and location.
public struct ListPrivateConnectionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent that owns the collection of private connections.
  public var parent: Swift.String = Swift.String()

  /// Maximum number of private connections to return.
  /// If unspecified, at most 50 private connections that are returned.
  /// The maximum value is 1000; values above 1000 are coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Page token received from a previous `ListPrivateConnections` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `ListPrivateConnections` must match the call that provided the page
  /// token.
  public var pageToken: Swift.String = Swift.String()

  /// A filter expression that filters private connections listed in the
  /// response. The expression must specify the field name, a comparison
  /// operator, and the value that you want to use for filtering. The value must
  /// be a string, a number, or a boolean. The comparison operator must be either
  /// =, !=, >, or <. For example, list private connections created this year by
  /// specifying **createTime %gt; 2021-01-01T00:00:00.000000000Z**.
  public var filter: Swift.String = Swift.String()

  /// Order by fields for the result.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListPrivateConnectionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListPrivateConnectionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ListPrivateConnectionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
