// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Definition of a transformation that is to be applied to a group of entities
/// in the source schema. Several such transformations can be applied to an
/// entity sequentially to define the corresponding entity in the target schema.
public struct MappingRule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Full name of the mapping rule resource, in the form of:
  /// projects/{project}/locations/{location}/conversionWorkspaces/{set}/mappingRule/{rule}.
  public var name: Swift.String = Swift.String()

  /// Optional. A human readable name
  public var displayName: Swift.String = Swift.String()

  /// Optional. The mapping rule state
  public var state: MappingRule.State = MappingRule.State()

  /// Required. The rule scope
  public var ruleScope: DatabaseEntityType = DatabaseEntityType()

  /// Required. The rule filter
  public var filter: MappingRuleFilter? = nil

  /// Required. The order in which the rule is applied. Lower order rules are
  /// applied before higher value rules so they may end up being overridden.
  public var ruleOrder: Swift.Int64 = Swift.Int64()

  /// Output only. The revision ID of the mapping rule.
  /// A new revision is committed whenever the mapping rule is changed in any
  /// way. The format is an 8-character hexadecimal string.
  public var revisionId: Swift.String = Swift.String()

  /// Output only. The timestamp that the revision was created.
  public var revisionCreateTime: GoogleWKT.Timestamp? = nil

  /// The rule specific details.
  public var details: OneOf_Details? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MappingRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MappingRule().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let state = CodingKeys(stringValue: "state")
    static let ruleScope = CodingKeys(stringValue: "ruleScope")
    static let filter = CodingKeys(stringValue: "filter")
    static let ruleOrder = CodingKeys(stringValue: "ruleOrder")
    static let revisionId = CodingKeys(stringValue: "revisionId")
    static let revisionCreateTime = CodingKeys(stringValue: "revisionCreateTime")
    static let singleEntityRename = CodingKeys(stringValue: "singleEntityRename")
    static let multiEntityRename = CodingKeys(stringValue: "multiEntityRename")
    static let entityMove = CodingKeys(stringValue: "entityMove")
    static let singleColumnChange = CodingKeys(stringValue: "singleColumnChange")
    static let multiColumnDataTypeChange = CodingKeys(stringValue: "multiColumnDataTypeChange")
    static let conditionalColumnSetValue = CodingKeys(stringValue: "conditionalColumnSetValue")
    static let convertRowidColumn = CodingKeys(stringValue: "convertRowidColumn")
    static let setTablePrimaryKey = CodingKeys(stringValue: "setTablePrimaryKey")
    static let singlePackageChange = CodingKeys(stringValue: "singlePackageChange")
    static let sourceSqlChange = CodingKeys(stringValue: "sourceSqlChange")
    static let filterTableColumns = CodingKeys(stringValue: "filterTableColumns")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "state",
      "ruleScope",
      "filter",
      "ruleOrder",
      "revisionId",
      "revisionCreateTime",
      "singleEntityRename",
      "multiEntityRename",
      "entityMove",
      "singleColumnChange",
      "multiColumnDataTypeChange",
      "conditionalColumnSetValue",
      "convertRowidColumn",
      "setTablePrimaryKey",
      "singlePackageChange",
      "sourceSqlChange",
      "filterTableColumns",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(MappingRule.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(DatabaseEntityType.self, forKey: .ruleScope) {
      self.ruleScope = value
    }
    self.filter = try container.decodeIfPresent(MappingRuleFilter.self, forKey: .filter)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .ruleOrder) {
      self.ruleOrder = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revisionId) {
      self.revisionId = value
    }
    self.revisionCreateTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .revisionCreateTime)

    var details: OneOf_Details? = nil
    let detailsCheckAndSet = {
      if details != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'details'"))
      }
      details = $0
    }
    if let singleEntityRename = try container.decodeIfPresent(
      SingleEntityRename?.self, forKey: .singleEntityRename)
    {
      try detailsCheckAndSet(.singleEntityRename(singleEntityRename))
    }
    if let multiEntityRename = try container.decodeIfPresent(
      MultiEntityRename?.self, forKey: .multiEntityRename)
    {
      try detailsCheckAndSet(.multiEntityRename(multiEntityRename))
    }
    if let entityMove = try container.decodeIfPresent(EntityMove?.self, forKey: .entityMove) {
      try detailsCheckAndSet(.entityMove(entityMove))
    }
    if let singleColumnChange = try container.decodeIfPresent(
      SingleColumnChange?.self, forKey: .singleColumnChange)
    {
      try detailsCheckAndSet(.singleColumnChange(singleColumnChange))
    }
    if let multiColumnDataTypeChange = try container.decodeIfPresent(
      MultiColumnDatatypeChange?.self, forKey: .multiColumnDataTypeChange)
    {
      try detailsCheckAndSet(.multiColumnDataTypeChange(multiColumnDataTypeChange))
    }
    if let conditionalColumnSetValue = try container.decodeIfPresent(
      ConditionalColumnSetValue?.self, forKey: .conditionalColumnSetValue)
    {
      try detailsCheckAndSet(.conditionalColumnSetValue(conditionalColumnSetValue))
    }
    if let convertRowidColumn = try container.decodeIfPresent(
      ConvertRowIdToColumn?.self, forKey: .convertRowidColumn)
    {
      try detailsCheckAndSet(.convertRowidColumn(convertRowidColumn))
    }
    if let setTablePrimaryKey = try container.decodeIfPresent(
      SetTablePrimaryKey?.self, forKey: .setTablePrimaryKey)
    {
      try detailsCheckAndSet(.setTablePrimaryKey(setTablePrimaryKey))
    }
    if let singlePackageChange = try container.decodeIfPresent(
      SinglePackageChange?.self, forKey: .singlePackageChange)
    {
      try detailsCheckAndSet(.singlePackageChange(singlePackageChange))
    }
    if let sourceSqlChange = try container.decodeIfPresent(
      SourceSqlChange?.self, forKey: .sourceSqlChange)
    {
      try detailsCheckAndSet(.sourceSqlChange(sourceSqlChange))
    }
    if let filterTableColumns = try container.decodeIfPresent(
      FilterTableColumns?.self, forKey: .filterTableColumns)
    {
      try detailsCheckAndSet(.filterTableColumns(filterTableColumns))
    }
    self.details = details
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.ruleScope, forKey: .ruleScope)
    try container.encodeIfPresent(self.filter, forKey: .filter)
    try container.encode(self.ruleOrder, forKey: .ruleOrder)
    try container.encode(self.revisionId, forKey: .revisionId)
    try container.encodeIfPresent(self.revisionCreateTime, forKey: .revisionCreateTime)

    if let choice = self.details {
      switch choice {
      case .singleEntityRename(let value):
        try container.encode(value, forKey: .singleEntityRename)
      case .multiEntityRename(let value):
        try container.encode(value, forKey: .multiEntityRename)
      case .entityMove(let value):
        try container.encode(value, forKey: .entityMove)
      case .singleColumnChange(let value):
        try container.encode(value, forKey: .singleColumnChange)
      case .multiColumnDataTypeChange(let value):
        try container.encode(value, forKey: .multiColumnDataTypeChange)
      case .conditionalColumnSetValue(let value):
        try container.encode(value, forKey: .conditionalColumnSetValue)
      case .convertRowidColumn(let value):
        try container.encode(value, forKey: .convertRowidColumn)
      case .setTablePrimaryKey(let value):
        try container.encode(value, forKey: .setTablePrimaryKey)
      case .singlePackageChange(let value):
        try container.encode(value, forKey: .singlePackageChange)
      case .sourceSqlChange(let value):
        try container.encode(value, forKey: .sourceSqlChange)
      case .filterTableColumns(let value):
        try container.encode(value, forKey: .filterTableColumns)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The current mapping rule state such as enabled, disabled or deleted.
  public enum State: Codable, Equatable, Sendable {
    /// The state of the mapping rule is unknown.
    case unspecified
    /// The rule is enabled.
    case enabled
    /// The rule is disabled.
    case disabled
    /// The rule is logically deleted.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .deleted: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      case 3: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .enabled: return try container.encode("ENABLED")
      case .disabled: return try container.encode("DISABLED")
      case .deleted: return try container.encode("DELETED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The rule specific details.
  public enum OneOf_Details: Codable, Equatable, Sendable {
    /// Optional. Rule to specify how a single entity should be renamed.
    indirect case singleEntityRename(SingleEntityRename?)
    /// Optional. Rule to specify how multiple entities should be renamed.
    indirect case multiEntityRename(MultiEntityRename?)
    /// Optional. Rule to specify how multiple entities should be relocated into
    /// a different schema.
    indirect case entityMove(EntityMove?)
    /// Optional. Rule to specify how a single column is converted.
    indirect case singleColumnChange(SingleColumnChange?)
    /// Optional. Rule to specify how multiple columns should be converted to a
    /// different data type.
    indirect case multiColumnDataTypeChange(MultiColumnDatatypeChange?)
    /// Optional. Rule to specify how the data contained in a column should be
    /// transformed (such as trimmed, rounded, etc) provided that the data meets
    /// certain criteria.
    indirect case conditionalColumnSetValue(ConditionalColumnSetValue?)
    /// Optional. Rule to specify how multiple tables should be converted with an
    /// additional rowid column.
    indirect case convertRowidColumn(ConvertRowIdToColumn?)
    /// Optional. Rule to specify the primary key for a table
    indirect case setTablePrimaryKey(SetTablePrimaryKey?)
    /// Optional. Rule to specify how a single package is converted.
    indirect case singlePackageChange(SinglePackageChange?)
    /// Optional. Rule to change the sql code for an entity, for example,
    /// function, procedure.
    indirect case sourceSqlChange(SourceSqlChange?)
    /// Optional. Rule to specify the list of columns to include or exclude from
    /// a table.
    indirect case filterTableColumns(FilterTableColumns?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.MappingRule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
