// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A filter defining the entities that a mapping rule should be applied to.
/// When more than one field is specified, the rule is applied only to
/// entities which match all the fields.
public struct MappingRuleFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The rule should be applied to entities whose parent entity
  /// (fully qualified name) matches the given value.
  /// For example, if the rule applies to a table entity, the expected value
  /// should be a schema (schema). If the rule applies to a column or index
  /// entity, the expected value can be either a schema (schema) or a table
  /// (schema.table)
  public var parentEntity: Swift.String = Swift.String()

  /// Optional. The rule should be applied to entities whose non-qualified name
  /// starts with the given prefix.
  public var entityNamePrefix: Swift.String = Swift.String()

  /// Optional. The rule should be applied to entities whose non-qualified name
  /// ends with the given suffix.
  public var entityNameSuffix: Swift.String = Swift.String()

  /// Optional. The rule should be applied to entities whose non-qualified name
  /// contains the given string.
  public var entityNameContains: Swift.String = Swift.String()

  /// Optional. The rule should be applied to specific entities defined by their
  /// fully qualified names.
  public var entities: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MappingRuleFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MappingRuleFilter().with { $0.parentEntity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parentEntity = CodingKeys(stringValue: "parentEntity")
    static let entityNamePrefix = CodingKeys(stringValue: "entityNamePrefix")
    static let entityNameSuffix = CodingKeys(stringValue: "entityNameSuffix")
    static let entityNameContains = CodingKeys(stringValue: "entityNameContains")
    static let entities = CodingKeys(stringValue: "entities")

    static let _knownKeys: Set<Swift.String> = [
      "parentEntity",
      "entityNamePrefix",
      "entityNameSuffix",
      "entityNameContains",
      "entities",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentEntity) {
      self.parentEntity = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entityNamePrefix) {
      self.entityNamePrefix = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entityNameSuffix) {
      self.entityNameSuffix = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entityNameContains) {
      self.entityNameContains = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .entities) {
      self.entities = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parentEntity, forKey: .parentEntity)
    try container.encode(self.entityNamePrefix, forKey: .entityNamePrefix)
    try container.encode(self.entityNameSuffix, forKey: .entityNameSuffix)
    try container.encode(self.entityNameContains, forKey: .entityNameContains)
    try container.encode(self.entities, forKey: .entities)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.MappingRuleFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
