// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Error message of a verification Migration job.
public struct MigrationJobVerificationError: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. An instance of ErrorCode specifying the error that occurred.
  public var errorCode: MigrationJobVerificationError.ErrorCode =
    MigrationJobVerificationError.ErrorCode()

  /// Output only. A formatted message with further details about the error and a
  /// CTA.
  public var errorMessage: Swift.String = Swift.String()

  /// Output only. A specific detailed error message, if supplied by the engine.
  public var errorDetailMessage: Swift.String = Swift.String()

  /// Initialize a new instance of `MigrationJobVerificationError`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MigrationJobVerificationError().with { $0.errorCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A general error code describing the type of error that occurred.
  public enum ErrorCode: Codable, Equatable, Sendable {
    /// An unknown error occurred
    case unspecified
    /// We failed to connect to one of the connection profile.
    case connectionFailure
    /// We failed to authenticate to one of the connection profile.
    case authenticationFailure
    /// One of the involved connection profiles has an invalid configuration.
    case invalidConnectionProfileConfig
    /// The versions of the source and the destination are incompatible.
    case versionIncompatibility
    /// The types of the source and the destination are incompatible.
    case connectionProfileTypesIncompatibility
    /// No pglogical extension installed on databases, applicable for postgres.
    case noPglogicalInstalled
    /// pglogical node already exists on databases, applicable for postgres.
    case pglogicalNodeAlreadyExists
    /// The value of parameter wal_level is not set to logical.
    case invalidWalLevel
    /// The value of parameter shared_preload_libraries does not include
    /// pglogical.
    case invalidSharedPreloadLibrary
    /// The value of parameter max_replication_slots is not sufficient.
    case insufficientMaxReplicationSlots
    /// The value of parameter max_wal_senders is not sufficient.
    case insufficientMaxWalSenders
    /// The value of parameter max_worker_processes is not sufficient.
    case insufficientMaxWorkerProcesses
    /// Extensions installed are either not supported or having unsupported
    /// versions.
    case unsupportedExtensions
    /// Unsupported migration type.
    case unsupportedMigrationType
    /// Invalid RDS logical replication.
    case invalidRdsLogicalReplication
    /// The gtid_mode is not supported, applicable for MySQL.
    case unsupportedGtidMode
    /// The table definition is not support due to missing primary key or replica
    /// identity.
    case unsupportedTableDefinition
    /// The definer is not supported.
    case unsupportedDefiner
    /// Migration is already running at the time of restart request.
    case cantRestartRunningMigration
    /// The source already has a replication setup.
    case sourceAlreadySetup
    /// The source has tables with limited support.
    /// E.g. PostgreSQL tables without primary keys.
    case tablesWithLimitedSupport
    /// The source uses an unsupported locale.
    case unsupportedDatabaseLocale
    /// The source uses an unsupported Foreign Data Wrapper configuration.
    case unsupportedDatabaseFdwConfig
    /// There was an underlying RDBMS error.
    case errorRdbms
    /// The source DB size in Bytes exceeds a certain threshold. The migration
    /// might require an increase of quota, or might not be supported.
    case sourceSizeExceedsThreshold
    /// The destination DB contains existing databases that are conflicting with
    /// those in the source DB.
    case existingConflictingDatabases
    /// Insufficient privilege to enable the parallelism configuration.
    case parallelImportInsufficientPrivilege
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .connectionFailure: return 1
      case .authenticationFailure: return 2
      case .invalidConnectionProfileConfig: return 3
      case .versionIncompatibility: return 4
      case .connectionProfileTypesIncompatibility: return 5
      case .noPglogicalInstalled: return 7
      case .pglogicalNodeAlreadyExists: return 8
      case .invalidWalLevel: return 9
      case .invalidSharedPreloadLibrary: return 10
      case .insufficientMaxReplicationSlots: return 11
      case .insufficientMaxWalSenders: return 12
      case .insufficientMaxWorkerProcesses: return 13
      case .unsupportedExtensions: return 14
      case .unsupportedMigrationType: return 15
      case .invalidRdsLogicalReplication: return 16
      case .unsupportedGtidMode: return 17
      case .unsupportedTableDefinition: return 18
      case .unsupportedDefiner: return 19
      case .cantRestartRunningMigration: return 21
      case .sourceAlreadySetup: return 23
      case .tablesWithLimitedSupport: return 24
      case .unsupportedDatabaseLocale: return 25
      case .unsupportedDatabaseFdwConfig: return 26
      case .errorRdbms: return 27
      case .sourceSizeExceedsThreshold: return 28
      case .existingConflictingDatabases: return 29
      case .parallelImportInsufficientPrivilege: return 30
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ERROR_CODE_UNSPECIFIED"
      case .connectionFailure: return "CONNECTION_FAILURE"
      case .authenticationFailure: return "AUTHENTICATION_FAILURE"
      case .invalidConnectionProfileConfig: return "INVALID_CONNECTION_PROFILE_CONFIG"
      case .versionIncompatibility: return "VERSION_INCOMPATIBILITY"
      case .connectionProfileTypesIncompatibility: return "CONNECTION_PROFILE_TYPES_INCOMPATIBILITY"
      case .noPglogicalInstalled: return "NO_PGLOGICAL_INSTALLED"
      case .pglogicalNodeAlreadyExists: return "PGLOGICAL_NODE_ALREADY_EXISTS"
      case .invalidWalLevel: return "INVALID_WAL_LEVEL"
      case .invalidSharedPreloadLibrary: return "INVALID_SHARED_PRELOAD_LIBRARY"
      case .insufficientMaxReplicationSlots: return "INSUFFICIENT_MAX_REPLICATION_SLOTS"
      case .insufficientMaxWalSenders: return "INSUFFICIENT_MAX_WAL_SENDERS"
      case .insufficientMaxWorkerProcesses: return "INSUFFICIENT_MAX_WORKER_PROCESSES"
      case .unsupportedExtensions: return "UNSUPPORTED_EXTENSIONS"
      case .unsupportedMigrationType: return "UNSUPPORTED_MIGRATION_TYPE"
      case .invalidRdsLogicalReplication: return "INVALID_RDS_LOGICAL_REPLICATION"
      case .unsupportedGtidMode: return "UNSUPPORTED_GTID_MODE"
      case .unsupportedTableDefinition: return "UNSUPPORTED_TABLE_DEFINITION"
      case .unsupportedDefiner: return "UNSUPPORTED_DEFINER"
      case .cantRestartRunningMigration: return "CANT_RESTART_RUNNING_MIGRATION"
      case .sourceAlreadySetup: return "SOURCE_ALREADY_SETUP"
      case .tablesWithLimitedSupport: return "TABLES_WITH_LIMITED_SUPPORT"
      case .unsupportedDatabaseLocale: return "UNSUPPORTED_DATABASE_LOCALE"
      case .unsupportedDatabaseFdwConfig: return "UNSUPPORTED_DATABASE_FDW_CONFIG"
      case .errorRdbms: return "ERROR_RDBMS"
      case .sourceSizeExceedsThreshold: return "SOURCE_SIZE_EXCEEDS_THRESHOLD"
      case .existingConflictingDatabases: return "EXISTING_CONFLICTING_DATABASES"
      case .parallelImportInsufficientPrivilege: return "PARALLEL_IMPORT_INSUFFICIENT_PRIVILEGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ErrorCode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ERROR_CODE_UNSPECIFIED": self = .unspecified
      case "CONNECTION_FAILURE": self = .connectionFailure
      case "AUTHENTICATION_FAILURE": self = .authenticationFailure
      case "INVALID_CONNECTION_PROFILE_CONFIG": self = .invalidConnectionProfileConfig
      case "VERSION_INCOMPATIBILITY": self = .versionIncompatibility
      case "CONNECTION_PROFILE_TYPES_INCOMPATIBILITY": self = .connectionProfileTypesIncompatibility
      case "NO_PGLOGICAL_INSTALLED": self = .noPglogicalInstalled
      case "PGLOGICAL_NODE_ALREADY_EXISTS": self = .pglogicalNodeAlreadyExists
      case "INVALID_WAL_LEVEL": self = .invalidWalLevel
      case "INVALID_SHARED_PRELOAD_LIBRARY": self = .invalidSharedPreloadLibrary
      case "INSUFFICIENT_MAX_REPLICATION_SLOTS": self = .insufficientMaxReplicationSlots
      case "INSUFFICIENT_MAX_WAL_SENDERS": self = .insufficientMaxWalSenders
      case "INSUFFICIENT_MAX_WORKER_PROCESSES": self = .insufficientMaxWorkerProcesses
      case "UNSUPPORTED_EXTENSIONS": self = .unsupportedExtensions
      case "UNSUPPORTED_MIGRATION_TYPE": self = .unsupportedMigrationType
      case "INVALID_RDS_LOGICAL_REPLICATION": self = .invalidRdsLogicalReplication
      case "UNSUPPORTED_GTID_MODE": self = .unsupportedGtidMode
      case "UNSUPPORTED_TABLE_DEFINITION": self = .unsupportedTableDefinition
      case "UNSUPPORTED_DEFINER": self = .unsupportedDefiner
      case "CANT_RESTART_RUNNING_MIGRATION": self = .cantRestartRunningMigration
      case "SOURCE_ALREADY_SETUP": self = .sourceAlreadySetup
      case "TABLES_WITH_LIMITED_SUPPORT": self = .tablesWithLimitedSupport
      case "UNSUPPORTED_DATABASE_LOCALE": self = .unsupportedDatabaseLocale
      case "UNSUPPORTED_DATABASE_FDW_CONFIG": self = .unsupportedDatabaseFdwConfig
      case "ERROR_RDBMS": self = .errorRdbms
      case "SOURCE_SIZE_EXCEEDS_THRESHOLD": self = .sourceSizeExceedsThreshold
      case "EXISTING_CONFLICTING_DATABASES": self = .existingConflictingDatabases
      case "PARALLEL_IMPORT_INSUFFICIENT_PRIVILEGE": self = .parallelImportInsufficientPrivilege
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ErrorCode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .connectionFailure
      case 2: self = .authenticationFailure
      case 3: self = .invalidConnectionProfileConfig
      case 4: self = .versionIncompatibility
      case 5: self = .connectionProfileTypesIncompatibility
      case 7: self = .noPglogicalInstalled
      case 8: self = .pglogicalNodeAlreadyExists
      case 9: self = .invalidWalLevel
      case 10: self = .invalidSharedPreloadLibrary
      case 11: self = .insufficientMaxReplicationSlots
      case 12: self = .insufficientMaxWalSenders
      case 13: self = .insufficientMaxWorkerProcesses
      case 14: self = .unsupportedExtensions
      case 15: self = .unsupportedMigrationType
      case 16: self = .invalidRdsLogicalReplication
      case 17: self = .unsupportedGtidMode
      case 18: self = .unsupportedTableDefinition
      case 19: self = .unsupportedDefiner
      case 21: self = .cantRestartRunningMigration
      case 23: self = .sourceAlreadySetup
      case 24: self = .tablesWithLimitedSupport
      case 25: self = .unsupportedDatabaseLocale
      case 26: self = .unsupportedDatabaseFdwConfig
      case 27: self = .errorRdbms
      case 28: self = .sourceSizeExceedsThreshold
      case 29: self = .existingConflictingDatabases
      case 30: self = .parallelImportInsufficientPrivilege
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .connectionFailure: return try container.encode(1)
      case .authenticationFailure: return try container.encode(2)
      case .invalidConnectionProfileConfig: return try container.encode(3)
      case .versionIncompatibility: return try container.encode(4)
      case .connectionProfileTypesIncompatibility: return try container.encode(5)
      case .noPglogicalInstalled: return try container.encode(7)
      case .pglogicalNodeAlreadyExists: return try container.encode(8)
      case .invalidWalLevel: return try container.encode(9)
      case .invalidSharedPreloadLibrary: return try container.encode(10)
      case .insufficientMaxReplicationSlots: return try container.encode(11)
      case .insufficientMaxWalSenders: return try container.encode(12)
      case .insufficientMaxWorkerProcesses: return try container.encode(13)
      case .unsupportedExtensions: return try container.encode(14)
      case .unsupportedMigrationType: return try container.encode(15)
      case .invalidRdsLogicalReplication: return try container.encode(16)
      case .unsupportedGtidMode: return try container.encode(17)
      case .unsupportedTableDefinition: return try container.encode(18)
      case .unsupportedDefiner: return try container.encode(19)
      case .cantRestartRunningMigration: return try container.encode(21)
      case .sourceAlreadySetup: return try container.encode(23)
      case .tablesWithLimitedSupport: return try container.encode(24)
      case .unsupportedDatabaseLocale: return try container.encode(25)
      case .unsupportedDatabaseFdwConfig: return try container.encode(26)
      case .errorRdbms: return try container.encode(27)
      case .sourceSizeExceedsThreshold: return try container.encode(28)
      case .existingConflictingDatabases: return try container.encode(29)
      case .parallelImportInsufficientPrivilege: return try container.encode(30)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.MigrationJobVerificationError"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
