// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Specifies connection parameters required specifically for PostgreSQL
/// databases.
public struct PostgreSqlConnectionProfile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The IP or hostname of the source PostgreSQL database.
  public var host: Swift.String = Swift.String()

  /// Required. The network port of the source PostgreSQL database.
  public var port: Swift.Int32 = Swift.Int32()

  /// Required. The username that Database Migration Service will use to connect
  /// to the database. The value is encrypted when stored in Database Migration
  /// Service.
  public var username: Swift.String = Swift.String()

  /// Required. Input only. The password for the user that Database Migration
  /// Service will be using to connect to the database. This field is not
  /// returned on request, and the value is encrypted when stored in Database
  /// Migration Service.
  public var password: Swift.String = Swift.String()

  /// Output only. Indicates If this connection profile password is stored.
  public var passwordSet: Swift.Bool = Swift.Bool()

  /// SSL configuration for the destination to connect to the source database.
  public var ssl: SslConfig? = nil

  /// If the source is a Cloud SQL database, use this field to
  /// provide the Cloud SQL instance ID of the source.
  public var cloudSqlId: Swift.String = Swift.String()

  /// Output only. If the source is a Cloud SQL database, this field indicates
  /// the network architecture it's associated with.
  public var networkArchitecture: NetworkArchitecture = NetworkArchitecture()

  /// Connectivity options used to establish a connection to the database server.
  public var connectivity: OneOf_Connectivity? = nil

  /// Initialize a new instance of `PostgreSqlConnectionProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PostgreSqlConnectionProfile().with { $0.host = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case host = "host"
    case port = "port"
    case username = "username"
    case password = "password"
    case passwordSet = "passwordSet"
    case ssl = "ssl"
    case cloudSqlId = "cloudSqlId"
    case networkArchitecture = "networkArchitecture"
    case staticIpConnectivity = "staticIpConnectivity"
    case privateServiceConnectConnectivity = "privateServiceConnectConnectivity"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.host = try container.decode(Swift.String.self, forKey: .host)
    self.port = try container.decode(Swift.Int32.self, forKey: .port)
    self.username = try container.decode(Swift.String.self, forKey: .username)
    self.password = try container.decode(Swift.String.self, forKey: .password)
    self.passwordSet = try container.decode(Swift.Bool.self, forKey: .passwordSet)
    self.ssl = try container.decodeIfPresent(SslConfig.self, forKey: .ssl)
    self.cloudSqlId = try container.decode(Swift.String.self, forKey: .cloudSqlId)
    self.networkArchitecture = try container.decode(
      NetworkArchitecture.self, forKey: .networkArchitecture)

    var connectivity: OneOf_Connectivity? = nil
    let connectivityCheckAndSet = {
      if connectivity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'connectivity'"))
      }
      connectivity = $0
    }
    if let staticIpConnectivity = try container.decodeIfPresent(
      StaticIpConnectivity?.self, forKey: .staticIpConnectivity)
    {
      try connectivityCheckAndSet(.staticIpConnectivity(staticIpConnectivity))
    }
    if let privateServiceConnectConnectivity = try container.decodeIfPresent(
      PrivateServiceConnectConnectivity?.self, forKey: .privateServiceConnectConnectivity)
    {
      try connectivityCheckAndSet(
        .privateServiceConnectConnectivity(privateServiceConnectConnectivity))
    }
    self.connectivity = connectivity
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.host, forKey: .host)
    try container.encode(self.port, forKey: .port)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.password, forKey: .password)
    try container.encode(self.passwordSet, forKey: .passwordSet)
    try container.encode(self.ssl, forKey: .ssl)
    try container.encode(self.cloudSqlId, forKey: .cloudSqlId)
    try container.encode(self.networkArchitecture, forKey: .networkArchitecture)

    if let choice = self.connectivity {
      switch choice {
      case .staticIpConnectivity(let value):
        try container.encode(value, forKey: .staticIpConnectivity)
      case .privateServiceConnectConnectivity(let value):
        try container.encode(value, forKey: .privateServiceConnectConnectivity)
      }
    }
  }

  /// Connectivity options used to establish a connection to the database server.
  public enum OneOf_Connectivity: Codable, Equatable, Sendable {
    /// Static ip connectivity data (default, no additional details needed).
    indirect case staticIpConnectivity(StaticIpConnectivity?)
    /// Private service connect connectivity.
    indirect case privateServiceConnectConnectivity(PrivateServiceConnectConnectivity?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.PostgreSqlConnectionProfile"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
