// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for 'SeedConversionWorkspace' request.
public struct SeedConversionWorkspaceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the conversion workspace resource to seed with new database
  /// structure, in the form of:
  /// projects/{project}/locations/{location}/conversionWorkspaces/{conversion_workspace}.
  public var name: Swift.String = Swift.String()

  /// Should the conversion workspace be committed automatically after the
  /// seed operation.
  public var autoCommit: Swift.Bool = Swift.Bool()

  /// The input to be used for seeding the conversion workspace. The input can
  /// either be from the source or destination databases and it can be provided
  /// through a connection profile or a DDL file.
  public var seedFrom: OneOf_SeedFrom? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SeedConversionWorkspaceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SeedConversionWorkspaceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let autoCommit = CodingKeys(stringValue: "autoCommit")
    static let sourceConnectionProfile = CodingKeys(stringValue: "sourceConnectionProfile")
    static let destinationConnectionProfile = CodingKeys(
      stringValue: "destinationConnectionProfile")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "autoCommit",
      "sourceConnectionProfile",
      "destinationConnectionProfile",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .autoCommit) {
      self.autoCommit = value
    }

    var seedFrom: OneOf_SeedFrom? = nil
    let seedFromCheckAndSet = {
      if seedFrom != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'seedFrom'"))
      }
      seedFrom = $0
    }
    if let sourceConnectionProfile = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceConnectionProfile)
    {
      try seedFromCheckAndSet(.sourceConnectionProfile(sourceConnectionProfile))
    }
    if let destinationConnectionProfile = try container.decodeIfPresent(
      Swift.String.self, forKey: .destinationConnectionProfile)
    {
      try seedFromCheckAndSet(.destinationConnectionProfile(destinationConnectionProfile))
    }
    self.seedFrom = seedFrom
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.autoCommit, forKey: .autoCommit)

    if let choice = self.seedFrom {
      switch choice {
      case .sourceConnectionProfile(let value):
        try container.encode(value, forKey: .sourceConnectionProfile)
      case .destinationConnectionProfile(let value):
        try container.encode(value, forKey: .destinationConnectionProfile)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The input to be used for seeding the conversion workspace. The input can
  /// either be from the source or destination databases and it can be provided
  /// through a connection profile or a DDL file.
  public enum OneOf_SeedFrom: Codable, Equatable, Sendable {
    /// Optional. Fully qualified (Uri) name of the source connection profile.
    case sourceConnectionProfile(Swift.String)
    /// Optional. Fully qualified (Uri) name of the destination connection
    /// profile.
    case destinationConnectionProfile(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.SeedConversionWorkspaceRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
