// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Filter for fixed point number data types such as NUMERIC/NUMBER
public struct SourceNumericFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The filter will match columns with scale greater than or equal to
  /// this number.
  public var sourceMinScaleFilter: Swift.Int32 = Swift.Int32()

  /// Optional. The filter will match columns with scale smaller than or equal to
  /// this number.
  public var sourceMaxScaleFilter: Swift.Int32 = Swift.Int32()

  /// Optional. The filter will match columns with precision greater than or
  /// equal to this number.
  public var sourceMinPrecisionFilter: Swift.Int32 = Swift.Int32()

  /// Optional. The filter will match columns with precision smaller than or
  /// equal to this number.
  public var sourceMaxPrecisionFilter: Swift.Int32 = Swift.Int32()

  /// Required. Enum to set the option defining the datatypes numeric filter has
  /// to be applied to
  public var numericFilterOption: NumericFilterOption = NumericFilterOption()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SourceNumericFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceNumericFilter().with { $0.sourceMinScaleFilter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sourceMinScaleFilter = CodingKeys(stringValue: "sourceMinScaleFilter")
    static let sourceMaxScaleFilter = CodingKeys(stringValue: "sourceMaxScaleFilter")
    static let sourceMinPrecisionFilter = CodingKeys(stringValue: "sourceMinPrecisionFilter")
    static let sourceMaxPrecisionFilter = CodingKeys(stringValue: "sourceMaxPrecisionFilter")
    static let numericFilterOption = CodingKeys(stringValue: "numericFilterOption")

    static let _knownKeys: Set<Swift.String> = [
      "sourceMinScaleFilter",
      "sourceMaxScaleFilter",
      "sourceMinPrecisionFilter",
      "sourceMaxPrecisionFilter",
      "numericFilterOption",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .sourceMinScaleFilter) {
      self.sourceMinScaleFilter = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .sourceMaxScaleFilter) {
      self.sourceMaxScaleFilter = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .sourceMinPrecisionFilter)
    {
      self.sourceMinPrecisionFilter = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .sourceMaxPrecisionFilter)
    {
      self.sourceMaxPrecisionFilter = value
    }
    if let value = try container.decodeIfPresent(
      NumericFilterOption.self, forKey: .numericFilterOption)
    {
      self.numericFilterOption = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceMinScaleFilter, forKey: .sourceMinScaleFilter)
    try container.encode(self.sourceMaxScaleFilter, forKey: .sourceMaxScaleFilter)
    try container.encode(self.sourceMinPrecisionFilter, forKey: .sourceMinPrecisionFilter)
    try container.encode(self.sourceMaxPrecisionFilter, forKey: .sourceMaxPrecisionFilter)
    try container.encode(self.numericFilterOption, forKey: .numericFilterOption)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.SourceNumericFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
