// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Filter for fixed point number data types such as NUMERIC/NUMBER
public struct SourceNumericFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The filter will match columns with scale greater than or equal to
  /// this number.
  public var sourceMinScaleFilter: Swift.Int32 = Swift.Int32()

  /// Optional. The filter will match columns with scale smaller than or equal to
  /// this number.
  public var sourceMaxScaleFilter: Swift.Int32 = Swift.Int32()

  /// Optional. The filter will match columns with precision greater than or
  /// equal to this number.
  public var sourceMinPrecisionFilter: Swift.Int32 = Swift.Int32()

  /// Optional. The filter will match columns with precision smaller than or
  /// equal to this number.
  public var sourceMaxPrecisionFilter: Swift.Int32 = Swift.Int32()

  /// Required. Enum to set the option defining the datatypes numeric filter has
  /// to be applied to
  public var numericFilterOption: NumericFilterOption = NumericFilterOption()

  /// Initialize a new instance of `SourceNumericFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceNumericFilter().with { $0.sourceMinScaleFilter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.SourceNumericFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
