// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Table's parent is a schema.
public struct TableEntity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Table columns.
  public var columns: [ColumnEntity] = []

  /// Table constraints.
  public var constraints: [ConstraintEntity] = []

  /// Table indices.
  public var indices: [IndexEntity] = []

  /// Table triggers.
  public var triggers: [TriggerEntity] = []

  /// Custom engine specific features.
  public var customFeatures: GoogleCloudWKT.Struct? = nil

  /// Comment associated with the table.
  public var comment: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TableEntity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TableEntity().with { $0.columns = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let columns = CodingKeys(stringValue: "columns")
    static let constraints = CodingKeys(stringValue: "constraints")
    static let indices = CodingKeys(stringValue: "indices")
    static let triggers = CodingKeys(stringValue: "triggers")
    static let customFeatures = CodingKeys(stringValue: "customFeatures")
    static let comment = CodingKeys(stringValue: "comment")

    static let _knownKeys: Set<Swift.String> = [
      "columns",
      "constraints",
      "indices",
      "triggers",
      "customFeatures",
      "comment",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([ColumnEntity].self, forKey: .columns) {
      self.columns = value
    }
    if let value = try container.decodeIfPresent([ConstraintEntity].self, forKey: .constraints) {
      self.constraints = value
    }
    if let value = try container.decodeIfPresent([IndexEntity].self, forKey: .indices) {
      self.indices = value
    }
    if let value = try container.decodeIfPresent([TriggerEntity].self, forKey: .triggers) {
      self.triggers = value
    }
    self.customFeatures = try container.decodeIfPresent(
      GoogleCloudWKT.Struct.self, forKey: .customFeatures)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .comment) {
      self.comment = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.columns, forKey: .columns)
    try container.encode(self.constraints, forKey: .constraints)
    try container.encode(self.indices, forKey: .indices)
    try container.encode(self.triggers, forKey: .triggers)
    try container.encodeIfPresent(self.customFeatures, forKey: .customFeatures)
    try container.encode(self.comment, forKey: .comment)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.TableEntity"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
