// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Trigger is not used as an independent entity, it is retrieved as part of a
/// Table entity.
public struct TriggerEntity: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the trigger.
  public var name: Swift.String = Swift.String()

  /// The DML, DDL, or database events that fire the trigger, for example
  /// INSERT, UPDATE.
  public var triggeringEvents: [Swift.String] = []

  /// Indicates when the trigger fires, for example BEFORE STATEMENT, AFTER EACH
  /// ROW.
  public var triggerType: Swift.String = Swift.String()

  /// The SQL code which creates the trigger.
  public var sqlCode: Swift.String = Swift.String()

  /// Custom engine specific features.
  public var customFeatures: GoogleWKT.WKTStruct? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TriggerEntity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TriggerEntity().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let triggeringEvents = CodingKeys(stringValue: "triggeringEvents")
    static let triggerType = CodingKeys(stringValue: "triggerType")
    static let sqlCode = CodingKeys(stringValue: "sqlCode")
    static let customFeatures = CodingKeys(stringValue: "customFeatures")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "triggeringEvents",
      "triggerType",
      "sqlCode",
      "customFeatures",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .triggeringEvents) {
      self.triggeringEvents = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .triggerType) {
      self.triggerType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sqlCode) {
      self.sqlCode = value
    }
    self.customFeatures = try container.decodeIfPresent(
      GoogleWKT.WKTStruct.self, forKey: .customFeatures)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.triggeringEvents, forKey: .triggeringEvents)
    try container.encode(self.triggerType, forKey: .triggerType)
    try container.encode(self.sqlCode, forKey: .sqlCode)
    try container.encodeIfPresent(self.customFeatures, forKey: .customFeatures)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.TriggerEntity"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
