// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// UDT's parent is a schema.
public struct UDTEntity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The SQL code which creates the udt.
  public var udtSqlCode: Swift.String = Swift.String()

  /// The SQL code which creates the udt body.
  public var udtBody: Swift.String = Swift.String()

  /// Custom engine specific features.
  public var customFeatures: GoogleCloudWKT.Struct? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `UDTEntity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UDTEntity().with { $0.udtSqlCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let udtSqlCode = CodingKeys(stringValue: "udtSqlCode")
    static let udtBody = CodingKeys(stringValue: "udtBody")
    static let customFeatures = CodingKeys(stringValue: "customFeatures")

    static let _knownKeys: Set<Swift.String> = [
      "udtSqlCode",
      "udtBody",
      "customFeatures",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .udtSqlCode) {
      self.udtSqlCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .udtBody) {
      self.udtBody = value
    }
    self.customFeatures = try container.decodeIfPresent(
      GoogleCloudWKT.Struct.self, forKey: .customFeatures)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.udtSqlCode, forKey: .udtSqlCode)
    try container.encode(self.udtBody, forKey: .udtBody)
    try container.encodeIfPresent(self.customFeatures, forKey: .customFeatures)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.UDTEntity"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
