// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A list of values to filter by in ConditionalColumnSetValue
public struct ValueListFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Indicates whether the filter matches rows with values that are
  /// present in the list or those with values not present in it.
  public var valuePresentList: ValuePresentInList = ValuePresentInList()

  /// Required. The list to be used to filter by
  public var values: [Swift.String] = []

  /// Required. Whether to ignore case when filtering by values. Defaults to
  /// false
  public var ignoreCase: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ValueListFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValueListFilter().with { $0.valuePresentList = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let valuePresentList = CodingKeys(stringValue: "valuePresentList")
    static let values = CodingKeys(stringValue: "values")
    static let ignoreCase = CodingKeys(stringValue: "ignoreCase")

    static let _knownKeys: Set<Swift.String> = [
      "valuePresentList",
      "values",
      "ignoreCase",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(ValuePresentInList.self, forKey: .valuePresentList)
    {
      self.valuePresentList = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .values) {
      self.values = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .ignoreCase) {
      self.ignoreCase = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.valuePresentList, forKey: .valuePresentList)
    try container.encode(self.values, forKey: .values)
    try container.encode(self.ignoreCase, forKey: .ignoreCase)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.ValueListFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
