// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// VM creation configuration message
public struct VmCreationConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. VM instance machine type to create.
  public var vmMachineType: Swift.String = Swift.String()

  /// The Google Cloud Platform zone to create the VM in.
  public var vmZone: Swift.String = Swift.String()

  /// The subnet name the vm needs to be created in.
  public var subnet: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VmCreationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VmCreationConfig().with { $0.vmMachineType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vmMachineType = CodingKeys(stringValue: "vmMachineType")
    static let vmZone = CodingKeys(stringValue: "vmZone")
    static let subnet = CodingKeys(stringValue: "subnet")

    static let _knownKeys: Set<Swift.String> = [
      "vmMachineType",
      "vmZone",
      "subnet",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmMachineType) {
      self.vmMachineType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmZone) {
      self.vmZone = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnet) {
      self.subnet = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.vmMachineType, forKey: .vmMachineType)
    try container.encode(self.vmZone, forKey: .vmZone)
    try container.encode(self.subnet, forKey: .subnet)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.clouddms.v1.VmCreationConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
